### ISSUE TITLE
Android 6.0 App crashes after update from v054c to v055

### ISSUE THREAD

**Issue by barkoder** [celzero/rethink-app#1010]
Upgraded from v054c to v055

App crashes when "Logs" is clicked and when "Apps" is clicked

I cleared the app's cache and data destroying ALL my settings. :(

And tried again.

App still crashes when "Logs" is clicked and when "Apps" is clicked.

Video attached.

Do you test on Android 6.0 during development ?

https://github.com/celzero/rethink-app/assets/70430094/feff7e69-b7e7-4527-b4ae-c1b231cb058f

Thanks.

**Comment by ignoramous** [comment]
> Do you test on Android 6.0 during development ?

No, we don't have an Android 6 handy to test it every release, unfortunately. We do test it in a virtual machine, though, but it isn't quite the same.

> App still crashes when "Logs" is clicked and when "Apps" is clicked.

Sounds like database upgrade failure. If you're comfortable sharing a [bugreport](https://developer.android.com/studio/debug/bug-report) we'd appreciate it. Email it to `mz` at `celzero` dot `com`.

**Comment by barkoder** [comment]
@ignoramous

Sent.

Along with relevant PWs.

Hope it helps.

Thanks!

**Comment by barkoder** [comment]
@ignoramous

Just letting you know that the download link to the bug report expires in ~48 hours. So please get it before it expires.

Also the email I sent is without any context. That's my bad. But it'll be pretty easy to spot, with the link and two long PW .

Thanks!

**Comment by ignoramous** [comment]
> Just letting you know that the download link to the bug report expires in ~48 hours. So please get it before it expires.

Downloaded it. Thanks. Taking a look...

**Comment by hussainmohd-a** [comment]
Thank you for sharing the logs @barkoder. 

Fix: e214aa9
Fix: details 
While loading the apps screen and logs screen, an exception is being thrown due to the default icon that is displayed when an app icon is missing. This exception states that the required resource cannot be located. It appears that the Android support library is unable to identify the vector graphic that includes the `<aapt:attr>` attribute. The problem was resolved by substituting the problematic icon with a different one. Interestingly, this problem did not arise when using Android Gradle version 7 or earlier, especially when the _desugaring_ feature was enabled.

**Comment by barkoder** [comment]
Thanks @hussainmohd-a

I look forward to the update on F-Droid.
