### ISSUE TITLE
WireGuard turns itself ON

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#1101]
A user says,

> @aliakbarmurtaza i am unable to disable wireguard proxy, it automatically turns  back on

Not much known about when or how it happens.

**Comment by hussainmohd-a** [comment]
Closing this issue due to insufficient information for debugging.

In scenarios where the "always-on" mode is enabled, WireGuard automatically activates and prevents manual disabling until the "always-on" setting is turned off.

Please feel free to reopen with more specific information if further investigation is needed.
