### ISSUE TITLE
Apps with Universal Bypass still get blocked

### ISSUE THREAD

**Issue by najjara** [celzero/rethink-app#1181]
I have put Firefox on universal bypass (but I still want it to use the selected DNS service), but the connections going through are still getting filtered according to the enabled lists. The specific domain being blocked here is wrongly listed on the typosquatting list (it's a legitimate domain, I've contacted the maintainer of the list).
![img1](https://github.com/celzero/rethink-app/assets/12216960/c9c432fe-284a-4113-99f4-2a71e7700174)
Perhaps I'm not using the rules correctly, but I can't find anything in the FAQ or docs that explain them (although they're simple enough like this, unless I'm not understanding them correctly). A brief description of each of the rules would be helpful.

**Comment by ignoramous** [comment]
To bypass DNS blocks, choose `Bypass DNS and Firewall`. Due to how it is implement, this rule drains more battery than normal.

For a more power efficient solution, `trust` / `allow` the blocked domain *globally* instead: (add as a universal rule from *Configure* -> *Firewall* -> *IP & Port rules* -> swipe to *Domains* -> tap on `+` floating button in the bottom right corner).

> A brief description of each of the rules would be helpful.

We can sure do better with docs. Btw, these descriptions exist in-app. Tap on the `i` icon just below the search bar in *Apps* screen.

--

Closing this, since it isn't really an issue but a Q&A? Reopen if you have any specific request not answered above. Thanks.
