### ISSUE TITLE
Last updated filters

### ISSUE THREAD

**Issue by LovingNumbers** [celzero/rethink-app#1208]
Can we get for each list a last updated text? 
Just like nextdns in the corner would be nice!

**Comment by ignoramous** [comment]
> Can we get for each list a last updated text?

Today, for blocklists meant for the Rethink Android app, ALL blocklists are updated in one-shot. This is an optimization to compress the lists and merge them on our servers, rather than on Androids.

The code for [blocklists generation is here](https://github.com/serverless-dns/blocklists/) and the updates are automated (happens once every 8 days; [ex](https://github.com/serverless-dns/blocklists/actions/runs/3483431063/jobs/5826911591)).

>  Just like nextdns in the corner would be nice!

As for the resolver (server side), we're planning a major overhaul and push for daily updates of blocklists at the very least. That work is on hold due to ongoing issues with our Cloudflare account (which is operating in a limited capacity since Nov last year due to some "trust & safety" issues Cloudflare flagged our account for, which haven't been resolved, yet).

**Comment by LovingNumbers** [comment]
Thanks for the answer! I read the stuff about cloudflare a while ago but didn't know that it still isn't resolved really sucks hope it gets better.

**Comment by ignoramous** [comment]
Thanks. We are stuck in this rut, unfortunately. And other providers are not viable since it'd cost us 5x more than what Cloudflare charges us.

Closing... feel free to reopen.

**Comment by LovingNumbers** [comment]
Wanted to ask about something but didn't find a issue that already exists regarding my question so i use this one here.

![Rethink3.jpg](https://github.com/celzero/rethink-app/assets/144499593/c827551f-2f34-4ac8-9177-8cf58ecef7c3)

![Rethink2.jpg](https://github.com/celzero/rethink-app/assets/144499593/ad9afcfc-9386-4a68-9dfd-17e036e6af22)

These three show no entries even though when you click on them their website present plenty do you guys know why?


![Rethink.jpg](https://github.com/celzero/rethink-app/assets/144499593/75454667-c78c-4ff8-8a33-82dcbfd11d92)

![Rethink4.jpg](https://github.com/celzero/rethink-app/assets/144499593/a77bf413-a65b-4aac-ba50-75a2d1345479)


And here the fanboy tracking blocklist is not supported anymore + the Adrules China gives back a 404 are you aware of this?

**Comment by ignoramous** [comment]
> aware of this?

Wasn't. Tracking here: https://github.com/serverless-dns/blocklists/issues/168 Thanks.
