### ISSUE TITLE
orbot proxy deactivated at reboot

### ISSUE THREAD

**Issue by alexbodn** [celzero/rethink-app#1248]
helo friends, 

and a huge thank for rethinking security over narrow purpose vpn.

both my rethink and orbot are restarting on boot, however rethink disables orbot proxy since it seems to load later.

instead, i would ask the proxy in rethink be kept active, but just be used only when orbot is actually active too.

thank you in advance,
alex

**Comment by ignoramous** [comment]
We haven't implemented "Always-on" for other proxies other than *WireGuard* (#1049 / #1014).
- #1065

> i would ask the proxy in rethink be kept active, but just be used only when orbot is actually active too

As a work around, you can use the raw SOCKS5 to connect to Orbot, with this limitation:
- #1126 

Closing this issue as dup of #1065 (please follow there).

**Comment by alexbodn** [comment]
hello ignoramous,

i didn't mean to implement always on logic, quite the opposite.

i was asking to use the activated proxy while  it's active and bypass it if
not.

best regards,
alex

**Comment by ignoramous** [comment]
> while it's active ... bypass it if not

This isn't straight forward to do, because Rethink doesn't exactly know when Orbot *becomes* active. The efficient way of doing so is for the user has to "setup Orbot" via the UI (in Rethink) to trigger that detecting flow.

That said, if we find a better way, we'll try implementing it.

> didn't mean ... [the] always on logic, quite the opposite

Gotcha. A proxy with "Lockdown" mode turned OFF, which is also only implemented for WireGuard:
- #976 (track it here)

**Comment by alexbodn** [comment]
Ok, many thanks for the clarification.


alex
