### ISSUE TITLE
Blocked domains being resolved

### ISSUE THREAD

**Issue by xvoodoochildx** [celzero/rethink-app#1254]
While dns and firewall are both active domains in the Blocklists and also manually blocked in the firewall, are still being resolved.
This occurs in rethink plus and also in the full version with download Blocklists.
It's an issue with the latest 0.5.5c from gothub and playstore while the older fdriod version works fine 🤪😔

**Comment by ignoramous** [comment]
> This occurs in rethink plus and also in the full version with download Blocklists

Can you see if these domains are blocked even after you stop/start Rethink? It could be that these domains are resolved from existing *cached* answers.

If not, can you give examples of domains you expect to block which aren't? Thanks.

**Comment by ignoramous** [comment]
> This occurs in rethink plus and also in the full version with download Blocklists

Can you see if these domains are blocked even after you stop/start Rethink? It could be that these domains are resolved from existing *cached* answers.

If not, can you give examples of domains you expect to block which aren't? Thanks.

**Comment by ThreeDeeJay** [comment]
I also noticed domains (like `www.google.com`) blocked in apps (like Firefox below) are still being resolved, which seems unnecessary since the app isn't supposed to (and doesn't) connect to the blocked domain anyway 🤔 
Behavior remains even after restarting Rethink, also using RDNS Plus:

![image](https://github.com/celzero/rethink-app/assets/71472458/e9d6be20-171f-4c53-9674-479cb8a9512f)

![image](https://github.com/celzero/rethink-app/assets/71472458/10449b57-5229-401b-97a5-9af8da492d17)

![image](https://github.com/celzero/rethink-app/assets/71472458/f74634f5-35be-4780-973d-06d8be2adf7f)

**Comment by ignoramous** [comment]
This is because either:
- The domain in question (`www.google.com`) has been *Trusted* by some app.
    - In this case, *DNS logs* UI should show "May be blocked" against the domain (`www.google.com`) with *yellow* coloured left-hand side border.
- At least *one* app has been set to *Bypass DNS and Firewall*.

This is expected because there's no way to otherwise apply *Trust* / *Bypass* rules.

Closing this issue as it isn't unexpected what you're seeing. In case I misunderstood, feel free to reopen.

**Comment by ThreeDeeJay** [comment]
> This is because either:
> - The domain in question (`www.google.com`) has been _Trusted_ by some app.
>       - In this case, _DNS logs_ UI should show "May be blocked" against the domain (`www.google.com`) with _yellow_ coloured left-hand side border.

The weird thing is that even though I trusted `www.google.com` in other apps, none of them are shown in the Network tab, only Firefox. I even blocked that domain for every app I had allowed, but even after restarting Rethink/WiFi, it still resolves it (at non-0ms which I think means isn't cached) and it's not marked as Maybe blocked 🤔

> - At least _one_ app has been set to _Bypass DNS and Firewall_.
> This is expected because there's no way to otherwise apply _Trust_ / _Bypass_ rules.

The only apps I had set to bypass were Orbot/Tor browser (so they can connect despite bypassing the DNS which is blocked by the universal rule), but even after changing them to allow (which btw prevents them from connecting) the behavior above remains. 
Btw most of my apps are set to isolate (most without specified IP/domains so they're effectively blocked), and some are allowed (browsers/download managers) and some are blocked (apps with allowed IP/domains previously in Isolate, but that I'm now blocking temporarily)

Anyhow, perhaps there's something I haven't wrapped my head around, but I  just would expect DNS resolve attempts to not happen at all if the domain is blocked for the app that actively requested it, even if the domain is allowed for other apps, especially if they're not trying to connect 🤔

**Comment by ignoramous** [comment]
> perhaps there's something I haven't wrapped my head around, but I just would expect DNS resolve attempts to not happen at all if the domain is blocked for the app that actively requested it, even if the domain is allowed for other apps, especially if they're not trying to connect

By default (and apps like Telegram and WhatsApp can and do change this behaviour, but many don't) all DNS requests are sent by *Android OS* on behalf of apps. Individual apps aren't sending these requests and hence it is impossible to block or allow a DNS request as the identity of the app that sent the DNS request is *not* known (and so, per-app rules cannot be applied, only universal rules can).

**Comment by ThreeDeeJay** [comment]
> By default (and apps like Telegram and WhatsApp can and do change this behaviour, but many don't) all DNS requests are sent by _Android OS_ on behalf of apps. Individual apps aren't sending these requests and hence it is impossible to block or allow a DNS request as the identity of the app that sent the DNS request is _not_ known (and so, per-app rules cannot be applied, only universal rules can).

I see. I have noticed that even [Mercurygram](https://github.com/drizzt/Mercurygram) connects directly to IPs which is annoying, though I think it (or an older Telegram build?) did use DNS a while ago. Speaking of, I just tested it and there's a bunch of IPs contacted by Mercurygram in the Network tab, but there are no requests in the DNS tab, not even by the system, unknown or anything. Does that mean the app's using hard-coded IPs or how does it resolve them? does it happen outside ReThink's reach?🤔 

Also, I've noticed that sometimes, apps seem to attempt to connect through a different route, which gets blocked because of the unknown source universal rule, and I guess that's what you're referring to, though that's not what happens in Mercurygram

**Comment by ignoramous** [comment]
> Does that mean the app's using hard-coded IPs or how does it resolve them?

It could be doing both: Hardcode IPs (Instagram and WhatsApp do this). Or resolve them using its own DoH / DoT resolver (Telegram does this).

> does it happen outside ReThink's reach

Unlikely unless *Configure* -> *Network* -> *Enable network visibility* is enabled.

You may choose to turn ON *Block when DNS bypassed* universal (global) firewall rule to block these apps.
