### ISSUE TITLE
bug: overheating issue

### ISSUE THREAD

**Issue by AnonymousWP** [celzero/rethink-app#1321]
Since today (yesterday I started using this app) I'm facing overheating issues. I noticed incoming and outcoming traffic for no reason and AIDA64 showed me high CPU load.

I'm using the default blocklists on a OnePlus Nord 3 running Android 14.

**Comment by ignoramous** [comment]
> AIDA64 showed me high CPU load.

What's AIDA64? If it is an app, can you post screenshot of what exactly it is showing you?

> I noticed incoming and outcoming traffic for no reason

Rethink can't (and doesn't) encourage more traffic flow. Though, some apps don't like being firewalled and hammer away. You could consider [*Force Stop*](https://archive.is/FRibb)ping those.

**Comment by AnonymousWP** [comment]
> > AIDA64 showed me high CPU load.
> 
> What's AIDA64? If it is an app, can you post screenshot of what exactly it is showing you?

https://play.google.com/store/apps/details?id=com.finalwire.aida64. I can't reproduce the issue anymore though; I wiped data of the app, but anyway, the 'CPU' tab showed me a high clock speed for most cores, resulting in my device getting hot.

> > I noticed incoming and outcoming traffic for no reason
> 
> Rethink can't (and doesn't) encourage more traffic flow. Though, some apps don't like being firewalled and hammer away. You could consider [_Force Stop_](https://archive.is/FRibb)ping those.

Hmm, weird, because I didn't have this issue with Blokada (but who knows, maybe a different blocklist). And as soon as I stopped/paused Rethink, there was no more traffic. Dunno, it felt like there was some local routing on the device going on, including some extracting (maybe of lists?) resulting in high CPU load.

**Comment by ignoramous** [comment]
> because I didn't have this issue with Blokada

Rethink has a network firewall, too (which Blokada doesn't have).

If you only want DNS-based blocking, then use Rethink ind *DNS-only* mode (click on the *downward* pointing arrow next to the `STOP`/`START` button on Rethink's homescreen to select *DNS-only* mode).

> I stopped/paused Rethink, there was no more traffic

What traffic did you see in *Network Logs*? It was originating from which app? Did you take a video / screenshot / packet capture of "too much traffic"? If so, that might help us diagnose this.

> including some extracting (maybe of lists?)

Rethink doesn't do this.

> resulting in high CPU load

Going by the screenshots, the app you shared (aida64) cannot tell just which app was causing high CPU, can it? Not sure why you are *certain* Rethink caused it. Sure, *stopping* Rethink made a difference, but it could be some other app trying desperately to get past the firewall, flooding packets, and hence causing high CPU use.

All that said, entirely possible Rethink has some bug that causes it. But the information you're giving us is inadequate to root cause it any further.

**Comment by AnonymousWP** [comment]
I believe I disabled the firewall and only used DNS, but it has been quite a while ago that I had this issue and I'm not sure how I can reproduce this issue, unfortunately. :/ Didn't take screenshots or a screen record either. AIDA64 can't show which app is causing the high load, indeed. That's unfortunate. Because my bug report isn't sufficient and I can't reproduce this issue, I'm closing it for now.

Thanks for your relentless effort and detailed replies - I appreciate it.
