### ISSUE TITLE
Problems with connection to api.imgur.com/0.0.0.0:443

### ISSUE THREAD

**Issue by Ypot** [celzero/rethink-app#1344]
EDIT: see my own answer in the next post 

Apps are working fine, but I found one app that doesn't seem to work. My settings:

DNS+Firewall active
Firewall is set to work only when phone is blocked.
No DNS, no firewall bypassed. 
The app is allowed to connect. 
No special rules added.

I receive this message:
![Screenshot_2024-04-05-23-18-15-05_149ce9bb6466820157471dbc127b1572](https://github.com/celzero/rethink-app/assets/30699014/f4e75268-679a-43c1-9920-24156ba545c6)

**Comment by Ypot** [comment]
Ok, I have tried a different RDNS and it seems to work. 

Any advice to avoid such cases? 

Thanks.

**Comment by ignoramous** [comment]
> Any advice to avoid such cases?

Not sure I understand what error the app (which app?) is showing (in the screenshot you shared) to recommend mitigations.

Glad it somehow works with a "different RDNS" though (I assume you switched from `max` to `sky`)?

**Comment by Ypot** [comment]
That works, not sure why. 

And changing to RDNS Default (Max) from RDNSPLUS (where I have just: crypto and aggressive privacy collections) works too.

**Comment by ignoramous** [comment]
>  Surprising for me, since in RDNSPLUS I have selected just crypto and aggressive privacy collections.

`max` runs a recursive resovler on Fly and does DoT.

`sky` runs a stub resolver Cloudflare and does DoH. 

Due to cost issues since Nov ($1500/mo and the bills were only going up from there), the code that `sky` is running is not the same as `max`. We're working on to make sure both `sky` and `max` converge like before.

> And changing to RDNS Default (Max)

My guess is RDNS Default is blocking some domains that the app doesn't like. You'll to go through the *DNS Logs* (which unfortunately is thankless task) on your Android to find out which blocked domain (these appear with a red-coloured left-hand side border) is causing trouble (and "trust" / "allow" it by tapping on its entry in *DNS Logs* which should bring up a *bottomsheet* with a bunch of options including setting "trust" / "allow" rules).
- Alternatively, you can "Exclude" the app here which doesn't work.
- Or, switch to non-blocking DNS resolver like *Cloudflare* or *Quad9* or *System DNS*.

**Comment by Ypot** [comment]
Thanks. 

I like RethinkDNS a little more everyday, I am changing of firewall. :-)
