### ISSUE TITLE
Unable to connect to the IPv6

### ISSUE THREAD

**Issue by Dusk0531** [celzero/rethink-app#1377]
After ipv6 was turned on, Internet access was often unavailable, and it returned to normal after uninstalling and restarting. After a while, the problem reappeared.

**Comment by ignoramous** [comment]
Some people have reported that the newer version don't work on Mobile networks (which are likely to support IPv6). We are unsure why this happens because no one has yet shared reproducible steps or logs that'll help us debug this (unfortunately, this bug does not manifest in our test Android devices, making diagnosis impossible).

* Have you changed any setting in *Configure* -> *Network* from whatever was the default?
   * If so, which ones?
   * If not, then check if setting *Choose IP version* to *Auto* helps?
* Are you using `System DNS`?
   * If so, change DNS to some other upstream and see if things work?
* Are you using any Proxies?
   * If WireGuard, are you using it in *Advanced* or *Simple* mode?
* Check *DNS Logs* and *Network Logs*:
   * Do you even see *new* logs in realtime of the websites / apps you recently attempted to use which couldn't connect?
   * Do you spot connection errors? Tap on the entries shown, which should bring up a *bottomsheet*. The footer of the *bottomsheet* contains the final status of a *closed* connection (Network) / request (DNS).
* Are you using Rethink in DNS+Firewall, or Firewall-only, or DNS-only mode?
* Have you enabled *Block connections without VPN* (aka "Lockdown VPN" mode) from Android's Settings?
* Have you enabled any *Universal firewall rules* from *Configure* -> *Firewall*, if so which ones?
* Have you enabled *Advanced DNS filtering* from *Configure* -> *DNS*?

**Comment by Dusk0531** [comment]
This is my setting.












千灯.
***@***.***


---Original---
From: ***@***.***&gt;
Date: Wed, Apr 24, 2024 23:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [celzero/rethink-app] Unable to connect to the IPv6 (Issue #1377)




 
Some people have reported that the newer version don't work on Mobile networks (which are likely to support IPv6). We are unsure why this happens because no one has yet shared reproducible steps or logs that'll help us debug this (unfortunately, this bug does not manifest in our test Android devices, making diagnosis impossible).
  
Have you changed any setting in Configure -&gt; Network from whatever was the default?  
If so, which ones?
 
If not, then check if setting Choose IP version to Auto helps?
  
 
Are you using System DNS?  
If so, change DNS to some other upstream and see if things work?
  
 
Are you using any Proxies?  
If WireGuard, are you using it in Advanced or Simple mode?
  
 
Check DNS Logs and Network Logs:  
Do you even see new logs in realtime of the websites / apps you recently attempted to use which couldn't connect?
 
Do you spot connection errors? Tap on the entries shown, which should bring up a bottomsheet. The footer of the bottomsheet contains the final status of a closed connection (Network) / request (DNS).
  
 
Are you using Rethink in DNS+Firewall, or Firewall-only, or DNS-only mode?
 
Have you enabled Block connections without VPN (aka "Lockdown VPN" mode) from Android's Settings?
 
Have you enabled any Universal firewall rules from Configure -&gt; Firewall, if so which ones?
 
Have you enabled Advanced DNS filtering from Configure -&gt; DNS?

**Comment by ignoramous** [comment]
Please see if the version `v055j` ([github](https://github.com/celzero/rethink-app/releases/v0.5.5j), [website](https://rethinkdns.com/download)) fixes it for you?
