### ISSUE TITLE
Due to which list blocked

### ISSUE THREAD

**Issue by toas-koas** [celzero/rethink-app#1542]
RethinkDNS has always been displayed because of which list a DNS entry was blocked.
Doesn't seem to be the case anymore. Or am I the only one?

**Comment by ignoramous** [comment]
You should see them with *on-device blocklists*.

For *remote* blocklists, RDNS+ is running in restrictive mode due to mounting costs: https://www.reddit.com/r/rethinkdns/comments/17h2y6r/rethink_dns_resolver_costs_1500_per_month_to_run/ (today, we receive ~$50/mo, which is no where near enough to go back to full functionality).

Once we are done with #946, we plan to revisit our [server codebase](https://github.com/serverless-dns/serverless-dns) and try to optimize for cost and enable this and other features.

(closing as this is intentional, for the time being; please feel free to re-open if we misunderstood your query)
