### ISSUE TITLE
Lavabit encrypted proxy

### ISSUE THREAD

**Issue by sankhababu** [celzero/rethink-app#1558]
Is it possible to use Lavabit encrypted proxy through rethink-app?

**Comment by ignoramous** [comment]
Not possible as LavaBit Encrypted Proxy uses OpenVPN: https://github.com/lavabit/pahoehoe/blob/c681230/README.md#upstream-code

And even if Rethink did support OpenVPN (#64), LavaBit's fork of it is specifically GPLv3 licensed, which is incompatible with the Apache License Rethink uses.

(I am closing this issue as it isn't a feature request we see ourselves doing ourselves, especially since there's an added hurdle of license incompatibility).
