### ISSUE TITLE
App-lock not functioning properly

### ISSUE THREAD

**Issue by GreenLandisaLie** [celzero/rethink-app#1588]
First of all congratz for such an amazing software! Came across this by chance after trying to find a NoRoot-Firewall alternative because its not supported on my new phone and it turns out this is vastly superior! Loving it so far.

I'm on Android 12, app version 0.5.5e.

About the issue,

Expected app-lock behaviour:
The app-lock feature should prompt the user for unlock every single time the app is 'opened' after being 'closed' (or opened for the first time after booting the phone). Additionally, it should also ask for it when 'maximizing the app' after a certain amount of time has passed since the last time it was unlocked (time should be adjustable in the settings but something like 5-10min would do for most people).

Actual behaviour:
I don't even know. Most times it straight out just doesn't ask the user to unlock which renders it mostly useless.

Sorry if this is a duplicate issue - couldn't find anything about it though.

**Comment by ignoramous** [comment]
> (or opened for the first time after booting the phone).

This should already be the case, at least on the latest version, `v055n` (Play Store only has upto `v055e`).

> time should be adjustable in the settings but something like 5-10min would do for most people

Today, the default is 15mins. We thought about exposing a user customisable timeout between applocks, but it yet another setting when the app is already bogged down by too many tunable knobs.

> Sorry if this is a duplicate issue

We've since fixed at least one issue related to applock (which we haven't released to play store):

- #1058

See if the latest version `v055n` works? Or, wait for `v055o` to land in Play Store (a week or so from now).

Also, we do want to change how we handle applocks, but that work is pending (and not priority among other much severe open bugs / issues).

- #1362

**Comment by GreenLandisaLie** [comment]
Tested just now (still on 0.5.5e - will wait for the next week update). 

Seems to be working as intended after all, its just that 15min is WAY too much time though plus I'd like it to request authentication every time on 'app launch after manually closing' - which doesn't happen.

I'm sure you guys will improve the logic considerably when you find time to work on it.
Will close this issue since you already have a related one open.
