### ISSUE TITLE
[Feature Request]: Wireguard Configs

### ISSUE THREAD

**Issue by derei** [celzero/rethink-app#1610]
Just some quick suggestions to make life easier with multiple Wiregard configurations:

1. Automatic fallback to next config if one server is down. This would pair well with an option to manually sort configs in the list, based on fallback priority.
2. Automatic switching off current config when selecting a different config checkbox. Currently, one has to disable current config before enabling a different  one. This is a redundant step which could be automated by internal app logic.
3. Optiom for internet access cutoff during switching, to prevent leaks. I know there has been some discussion about a Lockdown feature for Wireguard, but I can't seem to find such feature (unless is being implemented under the hood, witout user control?)

**Comment by ignoramous** [comment]
> Automatic fallback to next config if one server is down.

This is already implemented between multiple *Always-on* WireGuards (*Advanced* mode).
- #1477 

Providing a sorting order is not something we're keen on implementing (mostly due to the complexity of the feature relative to its usefulness).

> Automatic switching off current config when selecting a different config checkbox

This was the previous behaviour (for *Simple* mode). We changed it because users hated accidentally turning off or turning to another WireGuard configuration without confirmation.

> Option for internet access cutoff during switching, to prevent leaks

Turn ON *Lockdown* for WireGuards running in *Advanced* mode. And make sure there's no *split tunnel* (that is, Lockdown WireGuard's *Peer* must be able to route all IPs ie `0.0.0.0` and/or `::`).
- #976 

(closing, as there isn't anything here for us to address; feel free to reopen if you think otherwise).
