### ISSUE TITLE
Not able to use split-tunneling

### ISSUE THREAD

**Issue by LoHub** [celzero/rethink-app#1687]
Rethink claim in hit README that:

> Rethink supports forwarding TCP and UDP connections over SOCKS5, HTTP CONNECT, and WireGuard tunnels. Split-tunneling further helps run multiple such tunnels at the same time and lets users route different apps over different tunnels. For example, one could route Firefox over SOCKS5 connecting to Tor, Netflix over WireGuard connecting through any popular VPN provider, and Telegram or WhatsApp over censorship-resistant HTTP CONNECT endpoints at the same time.

Unfortunately I tried to enable a Wireguard tunnel with an active connection on Orbot and I get this message.

> Stop other active proxies to enable Wireguard.

If I do the opposite, attempt to enable Orbot with Wireguard enabled, I have the following message:

> Connected to Wierguard. Turn it off to continue.

How I am suppose to proceed to use split-tunneling?

**Comment by ignoramous** [comment]
Rethink had this, but it got too complicated and confusing with folks complaining of "connection leaks" (when possibly there weren't any and they just misconfigured the app). We disabled multi-proxy for now, though, multi-WireGuard still works (via *Advanced*).

We'll possibly re-enable multi-proxy again, once WireGuard is stable enough.

I'll change the readme, too. Thanks.

Please track (closing this as dup, feel free to reopen):
- #1623

**Comment by pixincreate** [comment]
> multi-WireGuard still works (via Advanced).

it for some reason, does not work as intended (at least for me). i can only get 1 of 3 tunnels under `lockdown` work at a time. rest 2 just does not work (it says it is active after refreshing, but i get only only `conn_refused`). at present, i'm running a single tunnel in advanced just so that i can include apps.

device info: Bluejay (GrapheneOS -- exploit protection compatibility has been disabled, so should have nearly stock experience)

custom dns setup via `Other DNS` as `Private DNS` from `System Settings` fails `Rethink`.
have 4 universal firewall rules to block bypassed dns, newly added apps and etc.,

**Comment by ignoramous** [comment]
I take you're using `v055n`, the latest version published to F-Droid / Website?

> i can only get 1 of 3 tunnels under lockdown work at a time

There isn't any built-in limitation wrt WireGuard *Lockdown* mode that should prevent multi-WireGuard from working.

So, what you're seeing is definitely a bug or a misconfiguration.

See if `Listening Port`s of those WireGuards are conflicting with each other? If so, leave those empty (then save it before re-running it) for Rethink to pick ports for them on random.

If not, and if you're technical enough, you can observe the logcat output (put Rethink in *Very Verbose* mode in *Configure* -> *Settings* -> *Log level*) for "GoLog" or "wg:" to see if you spot anything.

> is this the [intended](https://github.com/celzero/rethink-app/issues/1023) behavior?

Not really. That's feature is wanting to add the *same* app to multiple WireGuard profiles at the *same* time and then load balance the app among them.

> custom dns setup via Other DNS as Private DNS from System Settings fails Rethink.
> have 4 universal firewall rules to block bypassed dns

*Private DNS* should work. It does not for you because the Universal (global) rule, *Block when DNS is bypassed*, may be blocking ALL connections since using Private DNS means Rethink's DNS setup has been bypassed.

**Comment by pixincreate** [comment]
> I take you're using v055n, the latest version published to F-Droid / Website?

yes

> See if Listening Ports of those WireGuards are conflicting with each other? If so, leave those empty (then save it before re-running it) for Rethink to pick ports for them on random.

Listen ports are empty, `random` values are being considered. Now, I do feel it must be a misconfiguration from my end. I tried setting it up again, it just worked now.

The moment I enable `Private DNS provider hostname`, the app explicitly asks me to `Turn off Private DNS`. 

> Block when DNS is bypassed, may be blocking ALL connections since using Private DNS means Rethink's DNS setup has been bypassed.

I've disabled this, as I prefer to have my browser use a different DNS resolver just so that not every request made is blocked (`t.me`, `t.co` kind of end points).

For some reason, having Rethink slows down the internet significantly.

Will keep you updated.

**Comment by pixincreate** [comment]
i guess, i'm better off with creating a new issue for this.
