### ISSUE TITLE
localsend only one-way visibility

### ISSUE THREAD

**Issue by bede112** [celzero/rethink-app#1704]
I have an issue with [localsend](https://localsend.org/) while using Rethink app on default mode.
The other devices on my local network can't see the device which is using the Rethink app.
The device which is using the Rethink app though can see all other devices on my network and i can successfully transfer files too.

Is there a setting on Rethink app that can make my under Rethink app device visible to the other devices on my local network?
I tried the app bypass settings and nothing changed.
(Of course when i stop the Rethink app, localsend works normally as advertised.)

Thank you

**Comment by ignoramous** [comment]
P2P apps may work in `v055o` where we've made *some* changes to allow for NAT traversals (which might help with P2P apps like *KDE Connect*, *Syncthing*, *localsend*, etc)

As workarounds, you can "Exclude" *localsend* (from *Configure* -> *Apps*) or enable "Do not route Private IPs" (in *Configure* -> *Network*).

Since we don't use *localsend* or other similar P2P apps ourselves, it is unlikely we fix what you're seeing anytime soon, especially in absence of a detailed technical bug report.

Closing this; please track dup at: 
- #577

**Comment by Tback1** [comment]
as #2289 the same question
