### ISSUE TITLE
10 Percent app doesn't work with RethinkDNS turned on

### ISSUE THREAD

**Issue by domharrington** [celzero/rethink-app#236]
Hey! I just started using this app the other day as a Netguard replacement.

I use a meditation app called 10 Percent and when RethinkDNS is turned on, any sessions that I play have a mysterious "Playback failed due to I/O error" come up which goes away when I turn off RethinkDNS. I've tried adding this app to the whitelist and it doesn't appear to make any difference. I assume this error is coming from the 10 Percent app, but could RethinkDNS be tampering or blocking something else?

The app is here: https://play.google.com/store/apps/details?id=com.changecollective.tenpercenthappier

Thanks in advance, loving it so far.

**Comment by ignoramous** [comment]
Hi,

Thanks for your kind words.

Can you please check if it is the DNS that's preventing `10 Percent` from working? One way to do would be to search DNS logs to see which domain blocks are causing issues with the app.

RethinkDNS doesn't yet support "allowlists" to overwrite domain blocks, but the next version, due March, would add support for it.

In the interim, you could consider setting custom blocklists either using `RethinkDNS Plus` (from the DNS' "Configure" page) in the app or adding custom DNS like Quad9 or AdGuard that are a little less aggressive.

Another solution is to "Exclude" `10 Percent` altogether from the RethinkDNS VPN jail. Check RethinkDNS' `Settings` page and you should find an entry that goes `Exclude apps from Firewall and DNS`.

Since you're coming from NetGuard, note that, NetGuard tracks and blocks `ICMP` and can do `IPv6`, but RethinkDNS doesn't, yet, do both. We are trying to rectify it by moving to Netstack for the underlying TCP/IP implementation. #89 

---

The Firewall "Whitelist" only exempts an app from _firewall rules_. We are revamping the UI here to make that obvious because folks get confused a lot. Especially since DNS is about to get its own "Whitelist" ("Allowlist").

**Comment by ignoramous** [comment]
Okay, so I installed the app and hit the error you described whilst playing video sessions.

That, I presume, happens because various subomains of `amplitude.com`, `apptimize.com`, `appsflyer.com`, `boltdns.net`, `branch.io`, `braze.com` et al are blocked by default blocklists that the app is probably wanting to connect to. All those domains are classified as "trackers" which is why they're blocked.

So:

Excluding `10 Percent` from the jail should work.

Or, using a DNS that isn't as aggressive in blocking trackers or does no blocking at all, should do too. 

---

That said, we are implementing a couple of features that would make this easier in future versions:

1. Allow users to cherry-pick domains to be allowed or blocked.
2. Detect a "Whitelisted" app is in the foreground and allow all requests (block none).

**Comment by hussainmohd-a** [comment]
Now, users can add domains to **allow/block** list _app-wise_ in `v054a`. We consider this issue to be resolved and therefore, closing it. However, if you encounter any further issues or require any clarification, please feel free to reopen the issue or create a new one.

**Comment by ignoramous** [comment]
> Detect a "Whitelisted" app is in the foreground and allow all requests (block none).

This has been implemented too. The setting is found in *Apps* -> [*app name*] -> *Bypass DNS and Firewall*.
