### ISSUE TITLE
Blocklists don't show up in DNS logs with RethinkDNS Plus

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#252]
Blocklists don't show up when RethinkDNS Plus is selected. This has happened across multiple clean builds.

The blocklists show up just fine for on-device blocks.

A possible scenario to reproduce this (unconfirmed):
1. Tap on the _Configure_ button against _RethinkDNS Plus_ in the DNS screen.
2. Do not add any lists and click `Cancel` or click `Done`.
3. Notice RethinkDNS Plus is _not_ set.
4. Tap on the _Configure_ again, but this time set some blocklists.

**Comment by hussainmohd-a** [comment]
Issue is fixed in d1a384662e12c40bc6065cd65107d43649e57081.

**Comment by ignoramous** [comment]
> Issue is fixed in [d1a3846](https://github.com/celzero/rethink-app/commit/d1a384662e12c40bc6065cd65107d43649e57081).

How?

**Comment by hussainmohd-a** [comment]
The download of filetag.json is initiated when the user clicks on Configure button. With the previous code, if the user press cancel before the download filetag.json file. The value for the downloaded time is updated but there is an error received in the receiver. 
The fix is such that, unless the value is received in the receiver that the file is downloaded, the download time is not updated. 
persistanceState.tempRemoteBlockListDownloadTime & persistentState.remoteBlockListDownloadTime.
