### ISSUE TITLE
Exclude ntp (udp port 123 from system process)

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [celzero/rethink-app#310]
Please let user or by default Exclude NTP (UDP port 123 from system process) because, if time is not in sync, no TLS connection will never succeed. orbot can't bootstrap. DNS (at least DoH) will fail because HTTPS will fail.

**Comment by ignoramous** [comment]
You mean, whitelist / allow all traffic on 123?

It is uncommon for apps to probe reserved ports to breach firewall rules, BTW, for example, webrtc apps using port `53` for `STUN`.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
I would like to exclude android NTP client from DNS forwarder. Without excluding **all** systems Apps connections. Since there's existing ecocide UDP Option already.

![0a53d846-d9cd-452b-8639-e8cef165e4cc.jpg](https://user-images.githubusercontent.com/46166740/123282506-db442e80-d50a-11eb-8cd4-f1ee8e62f8c1.jpg)
![63d3be67-d540-4a11-b626-422e9aa4572f.jpg](https://user-images.githubusercontent.com/46166740/123282525-e0a17900-d50a-11eb-881c-aa47388f5674.jpg)

Orbotdns
![a2d4ac37-7645-46ea-9d69-ae649e19f4c2.jpg](https://user-images.githubusercontent.com/46166740/123282569-ed25d180-d50a-11eb-9b95-cced68fe65d5.jpg)

**Comment by ignoramous** [comment]
Thanks. What Orbot's doing here (IPv4 --> IPv6) is probably a variation on DNS ALG (Application-level Gateway).

Btw, NTP bypass is now the default behaviour impl in #354 and expected to land in `v053g`. I am in two minds about this, because the behaviour now that leaks UDP over `123` by default... Remember, RethinkDNS does not inspect the packets on port `123` to check if it is indeed NTP. Any such "leaks" however would show up in `Network Logs`.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
Great, I saw its already implemented into v0.5.3g.

> I am in two minds about this, because the behaviour now leaks UDP over `123` by default for `System` components _and_ apps... Remember, RethinkDNS does not inspect the packets on port `123` to check if it is indeed NTP. Any such "leaks" however would show up in `Network Logs`.
> 

For the possible UDP:123 leaks, I was thinking about RethinkDNS. 
The smart solution of the DNS Firewall does not block anything except custom DNS but now allows to force use it by "Forward all traffic to port 53 to user-configured DNS endpoint." That's clever since some apps tried contact 8.8.8.8/8.8.4.4 on their own.
Its called RethinkDNS and not RethinkNTP. So you cannot cover any application layer protocols. But how about Idea of doing similar traffic forwarding by firewall for this type of traffic? "Forward all traffic to port 123 to (user-configured/default) NTP endpoint."

**Comment by ignoramous** [comment]
To minimize the leak, NTP is only allowed if coming from _System_ apps.

Btw, that's a good one, proxying to a custom NTP address: celzero/firestack#10

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> To minimize the leak, NTP is only allowed if coming from _System_ apps.
> 

I can see it actually works.
![I.jpg](https://user-images.githubusercontent.com/46166740/134775270-47a69ea2-fdf3-450f-bf57-ff68ffac9380.jpg)

_(Ignore the IP)_

**Comment by ignoramous** [comment]
Thanks for confirming. You should use the dark mode (:

> Another example, there is existing a DoH onion domain from cloudflare.
> https://dns4torpnlfs2ifuz2s2yf3fc7rdmsbhm6rw75euj35pac6ap25zgqad.onion
> https://developers.cloudflare.com/1.1.1.1/fun-stuff/dns-over-tor#dns-over-tcp-tls-and-https
> To use it in rethink app, it would need to speak tcp to orbot over socks5 but the DoH domain needs to be resolved beforehand? Orbot could resolve example

I didn't quite catch this. Btw, is there a pluggable DNS over Tor implementation? If so, we could expose that instead of going through the trouble of forwarding DNS over SOCKS5 (TCP) and haggling with conversion to UDP <-> TCP (because UDP packet-sizes are such that they cannot handle potentially longer TCP streams, which means extra code to handle those scenarios where a DNS response over TCP might potentially need to be split among various UDP packets. Even if done properly, it isn't clear if apps / OS' DNS client would know how to handle fragmented DNS response)
