### ISSUE TITLE
Rethink app need to rethink its filtering

### ISSUE THREAD

**Issue by strongok** [celzero/rethink-app#313]
As a long **NetGuard** user, I tried Rethink app from f-droid.

I had to uninstall Rethink and revert to NetGuard because there are 3 major and 2 minor problems.

Major:

1. Firewall is unusable with proxy settings

I go to settings and block all apps including system. I only allowed Browser app. Then, I activated Orbot integration inside your app. Rethink said all traffic is now routed over Tor.

The problem is all other apps! can connect to internet, not just Browser if HTTP proxy is enabled (orbot activated) Firewall is completely unusable.

When I disable orbot link, rethink block app's internet connection as advertised.

conclusion: if the HTTP proxy(orbot) is active, your app is ignoring firewall rules silently.

2. Unable to select anything for on-device filtering

When I select on-device filtering, your app said I need to download 50MB of data so I hit yes. The problem is the download never ends. I allowed internet connection for Download app, still didn't finish.

Why don't you let people which hosts file they want to use instead of downloading whole? entire? database??

3. App count (whitelisted, allowed, blocked) is unclear and not accurate

Your app doesn't show how many apps are blocked/allowed _clearly_. Group category is useless imho. Have a peek on Netguard's main UI. It supports filtering and user can see which apps are going to be allowed at a glance. I also have to argue that your app counter is not accurate until I "go back" and open UI again.

Minor:

1. Why can't I delete pre-configured DoH/DNSCrypt settings?

In "DNS66" app for example you can delete pre-configured DNS servers.
 
2. Why BasicRethink server's DoH is activated by default?

This thing should be user's default ISP _by default_. User should opt-in to use your server. Do you know GDPR? Why should I send my DNS query to your server on the first install?

**Comment by ignoramous** [comment]
Thanks. Could have been separate issues, but I'll split them when we get around to addressing them.

Here's my quick response:

> Firewall is unusable with (http) proxy settings

Yes, this is true because RethinkDNS does not implement http proxy but rather uses Android APIs to simply *set* one. Android's implementation is such that it doesn't send packets to be sent to the http-proxy through the tunnel to the VPN. In other words, Android isn't sending RethinkDNS the http-proxy traffic. And RethinkDNS cannot block what it doesn't see.

We may yet implement a http proxy within the app, but that's gets complicated with http/2; though I am sure there exists some neat golang implementations we could use. May be when we integrate either V2RayCore (#274) or Cloak (#51), we'd explore that option once again. See also #44 #55  

---

> Unable to select anything for on-device filtering

We moved to use Android's stock DownloadManager which seems to be broken on certain custom ROMs. It also breaks if UDP traffic is blocked. And if the VPN is running in "lockdown mode" (that is, "Block connections without VPN" is turned on from Android's VPN Settings). We would have to move to our own downloader, but this is unlikely to happen in the next couple months. See #314 

> Why don't you let people which hosts file they want to use instead 

This is planned. We haven't done this because it complicates edge-cases and user support when they can point to any url to download any blocklist file; especially at a time when the rest of the app's functionality is in a state of flux and complicated already. See #36 

> ...downloading whole? entire? database??

This is a highly compressed radix trie which lets us store all blocklists in memory to avoid hitting the disk on every DNS request. One advantage of this approach is, as we keep adding newer lists, the size increases linearly at worst, and sub-logarithmically at best. It took us 4 months to make the compression and searches work... :D I hope it is not all for naught. We still plan to compress the radix trie further by 20% at least, to reduce its size.

> App count (whitelisted, allowed, blocked) is unclear and not accurate

1. Yes, that piece of code isn't the greatest. We need to improve it, for sure.

2. Earlier, the app would listen on every package install and uninstall to keep that list up-to-date, but it quickly became obvious that it was a cause of battery drain. And so, we removed it at the cost of having stale data, because uninstalls and installs aren't all that frequent anyway to warrant that battery hit. Btw, the "Refresh" button next to the search bar (in the `ALL APPS` tab) in the Firewall screen, should sync up everything. Is that what you not observe?

---

> Your app doesn't show how many apps are blocked/allowed clearly.

There's a "filter" icon on the search bar (in the `ALL APPS` tab) in the Firewall screen that lets you see only the "firewalled" apps. That said, I get your point. We are in the process of overhauling the Firewall screen altogether. That's likely to land in the next two months. #308 #3 

---

>  Why can't I delete pre-configured DoH/DNSCrypt settings?

I think this may cause issues with database upgrades across versions if we let users delete presets. We could let users "tombstone" them though, that is merely hide it from the UI. Something we should consider doing but then we'd have to also add a new UI to "unhide" / "un-tombstone" those entries. I'd be happy to merge a pull-request on this, but unlikely to spend my own time working on it in the next few months at the very least.

>  Why BasicRethink server's DoH is activated by default?

I need to default to some DoH. Cannot fallback to OS or network-provided plain old DNS. This app is also a means to circumvent censorship. We do plan to build a "first-run" screen and prompt users to select a default DoH (like how [Nebulo](https://github.com/c4h4tr/Nebulo) does) among other settings. See also #211 #140 #139 #170 

Thanks again. Let us know if there's more you'd like to discuss.
