### ISSUE TITLE
Resolved IP being reversed in log-view

### ISSUE THREAD

**Issue by slcw** [celzero/rethink-app#369]
This is sort of an odd problem. It seems that the resolved IP for each query is being reversed on display in the log-view. For example, the host "oauth.reddit.com", which resolves to IP 151.101.69.140, is displayed as 140.69.101.151 in the log. This is happening with all queries, and it's affecting the associated country flag icons as well. The problem persists across DNS providers.

![Screenshot_20210908-150132_RethinkDNS](https://user-images.githubusercontent.com/87735441/132585961-37306ca4-f159-4a57-93e9-64b6f8718c10.jpg)

**Comment by ignoramous** [comment]
Yeah, we switched libraries that parses these IPs in `v053f`. And it turns out, the newer one likes little endianess, whilst the previous one was big endian by default.

And so, we have now switched to using what we were previously in a yet to release `v053g`. This fix is being reviewed as part of part-ii of a massive rewrite of the kotlin layers of the app in #354 (which is near completion).

Thanks for your detailed bug report, btw. Appreciate it.

Closing as dup of #357
