### ISSUE TITLE
DNS over 53?

### ISSUE THREAD

**Issue by zqpvr** [celzero/rethink-app#430]
When will or are you going to support this?

**Comment by ignoramous** [comment]
We do have the infrastructure to support it on the server/resolver side, but I don't think we ever will because of the amount of abuse a public DNS service has to deal with over unauthenticated UDP.

As for DNS over 53 on the app, that's already supported.

1. Tap on the "DNS" tile on the homescreen
2. Swipe to "Configure" tab
3. From the drop-down choose "DNS Proxy"
