### ISSUE TITLE
Inconsistent behavior with Start/Stop and 'Not Protected' 'Waiting' 'Starting' and 'Protected' 

### ISSUE THREAD

**Issue by DorianHeckler** [celzero/rethink-app#452]
Lineage 18.1 (Android 11)
Google Pixel 5a

Installed the app today and had a hard time understanding whether it was fully activating because the text under the Start/Stop button did not fully update.

Steps to reproduce:
1. Tap Stop button if RTDNS is started
2. Note 'Not Protected' text under button
3. Tap down arrow on Start button to open Choose Mode menu
4. Switch to DNS and Firewall setting if not already
5. Close Choose Mode menu
6. Tap Start
7. Note 'Not Protected' text changes to 'Waiting'
8. Open Choose Mode menu again
9. Change setting to Firewall and close Choose Mode menu
10. Note 'Waiting' changes to 'Protected'
11. Tap Stop
12. Note 'Protected' changes to 'Not Protected'
13. Open Choose Mode menu
14. Change setting to DNS
15. Tap Start
16. Note 'Not Protected' changes to 'Waiting'
17. Open Choose Mode menu
18. Change setting to DNS and Firewall and close Choose Mode menu
19. Note 'Waiting' changes to 'Starting'
20. Open Choose Mode menu
21. Change setting to Firewall, then without closing menu change back to DNS
22. Note 'Starting' changes to 'Protected'

At steps 7, is 'Waiting' the correct status? On step 7, why does it only update to 'Protected' after changing the mode to Firewall?

At step 16, is 'Waiting' the correct status? At step  19, is 'Starting' the correct status? Why does it only update to 'Protected' after changing the mode to Firewall and changing back?

In all cases, immediately after tapping Start the Android status bar seems to indicate the same thing: "This device is connected to RethinkDNS."

Also, the same 'fix' shown on line 21 for starting on DNS works when starting with DNS and Firewall — you can open the menu, switch to Firewall and switch back to DNS and Firewall, and the status shows 'Protected.'

**Comment by ignoramous** [comment]
Thanks for this detailed report (:

`Starting` -> The tunnel is being initialized.

`Waiting` -> Waiting for a DNS query

`Protected` -> Either DNS is working as intended, or Firewall is working as intended, or both.

`Not protected` -> Neither DNS nor Firewall is setup.

----

> At steps 7, is 'Waiting' the correct status?

Yes, it is. Since the app is `Waiting` for DNS queries at that point.

> ...why does it only update to 'Protected' after changing the mode to Firewall?

Since Firewall is setup already (and DNS has been disabled, and so, there's no point in `Waiting`, as it were).

> At step 16, is 'Waiting' the correct status?

Yes, it is, as the app is `Waiting` for DNS queries to serve.

> At step 19, is 'Starting' the correct status?

It is neither correct nor wrong. It may be indicative of tunnel restart (guessing).

> Why does it only update to 'Protected' after changing the mode to Firewall and changing back?

`Protected` is a state where either Firewall or DNS is up and working. In DNS' case, the app needs to have served at least one DNS query before it transitions from `Waiting` to `Protected`.

> Also, the same 'fix' shown on line 21 for starting on DNS works when starting with DNS and Firewall — you can open the menu, switch to Firewall and switch back to DNS and Firewall, and the status shows 'Protected.'

As expected, right?

----

I believe the whole protected, not protected, starting, waiting dance is super tricky or rather not coherently consistent?

**Comment by ignoramous** [comment]
I doubt there is a bug, as changing modes has worked fine since forever. What the statuses mean is mentioned in my comment above. 

That said, I see it is confusing, and so, I'll this bug open to track "unconfuse" it.

**Comment by DorianHeckler** [comment]
Here, I think I'm describing this issue with too much complexity. Let me describe it another way:

On my phone, if I have 'DNS and Firewall' selected in the Mode popup, when I tap Start the status never changes from 'Waiting.' No matter how long I let it sit, it never shows as 'Protected.'

The only way I've seen 'Protected' on my phone has been to do the trick I describe above with the Choose Mode menu.

**Comment by ignoramous** [comment]
Can you post a screenshot please, of the homescreen with 'Waiting'?

1. Is it "blue" in color or "red"?
2. Are you using _Private DNS_ (DoT) on Android 9+?

**Comment by ignoramous** [comment]
We've changed the status modes (removed "waiting" and "starting") to avoid causing confusion.
