### ISSUE TITLE
DB schema for IP addr

### ISSUE THREAD

**Issue by hussainmohd-a** [celzero/rethink-app#495]
Convert IP address stored in database from String to Integer/bytes.

**Comment by ignoramous** [comment]
According to the sqlite3 [documentation](https://www.sqlite.org/datatype3.html), `BLOB` uses `memcp` for byte-by-byte comparisions. This works nicely for IPv4 / IPv6 / IPv4 in IPv6.

**Comment by ignoramous** [comment]
Since we do a bunch of string-related filtering, there'd be too many conversions from byte -> strings for IPs anyway. Even if storage of IPs as strings is inefficient (and also inefficient when making firewall decisions based on IP subnets / masks etc), for workloads that we see on Androids, it isn't anything too critical or slow. 

We'll revisit doing this in case we see reports of the database being too huge (network + dns logs dbs collectively grow by 2.6MB per day on usual use) or too slow to query. Closing for now...
