### ISSUE TITLE
Adaptive Icon

### ISSUE THREAD

**Issue by ghost** [celzero/rethink-app#511]
Could you make the app icon adaptive so it follows the shape of other app icons?

**Comment by JM480** [comment]
The icon is in a bubble when icon shapes are changed.

**Comment by ignoramous** [comment]
Can you please share a screenshot? I use Lawnchair 2 with squircle-shaped icon pack. Rethink's icon doesn't look any more different than the other squircle ones.

**Comment by JM480** [comment]
![Screenshot_20220908-165700_Trebuchet](https://user-images.githubusercontent.com/84468401/189224799-61d549b4-f199-44aa-9079-a1a266c78f6b.png)
The icon is in a bubble unlike the other icons.

**Comment by ignoramous** [comment]
Gotcha. Thanks for sharing the screenshot. I don't know what needs to be done, but I'll keep looking.

**Comment by PandoraHayami** [comment]
It shouldn't be that difficult, to my knowledge, you would need a white background and the RethinkDNS logo transparent and, with the appropriate names and sizes, Android should do the rest.

**Comment by ignoramous** [comment]
> It shouldn't be that difficult, to my knowledge, you would need a white background and the RethinkDNS logo transparent and, with the appropriate names and sizes, Android should do the rest.

Difficulty is relative isn't it? I wouldn't know how to do that (I haven't managed to)... Not sure if the lead developer on the app knows how to do so pixel-perfectly, either.

**Comment by ignoramous** [comment]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by hussainmohd-a** [comment]
Introduced new adaptive icons for various screen resolutions. #[b927908](https://github.com/hussainmohd-a/rethink-app/commit/b927908d1097aa09b14dcac0b06eee26b0fbcc0b)

**Comment by PandoraPandorita** [comment]
The adaptive icon doesn't work in the latest update.

**Comment by ignoramous** [comment]
Not sure what has changed, since the drawables are intact... will take a look.

**Comment by ignoramous** [comment]
@PandoraPandorita I rollbacked to `v053n` and adaptive icon is working...? As in, I drag the icon around and I can see the logo within it bounce about in *Lawnchair 2*... What are you seeing instead?

**Comment by PandoraPandorita** [comment]
Guess should've specified lol.

Here's the icon from 053L on my phone's stock launcher:

![Screenshots_2023-01-26-22-08-20](https://user-images.githubusercontent.com/79670265/215008885-9e61a41b-c1a9-47a5-8287-5322577c371c.png)

That's what's expected, now, here's on my tablet which uses Lawnchair 10 with Quickswitch and other apps as reference:

![IMG_20230126_221224](https://user-images.githubusercontent.com/79670265/215008963-f4a16045-8ae5-456b-8a42-006400969186.jpg)

(The icon shape was changed for this example)

Now, here is what 053M and 053N looks like on my phone's stock launcher:

![Screenshots_2023-01-26-22-13-20](https://user-images.githubusercontent.com/79670265/215009055-26030efd-34ea-4bee-b304-9ce381930e6b.png)

And again, here's in my tablet with the same setup and 053N version of the app with others as reference:

![IMG_20230126_221245](https://user-images.githubusercontent.com/79670265/215009134-02975b2f-3768-466b-af29-da8f2f032d55.jpg)

Other details that may help are that these are the F-Droid builds, and that both of my devices run Android 10, my tablet runs a really stock-like Android and my phone runs under LG UX, just if it helps.

Also, it took a bit for the response since using this crappy LG to report issues is a torture.

**Comment by ignoramous** [comment]
Wow. Thanks for the screenshots. Appreciate you going through the hassle of it all.

We will take a look. From the code at least, we haven't removed those icon drawables. May be something in the build system (which we changed quite a bit with the previous update, `v053m`) is mucking with those. We'll check and get back.

**Comment by hussainmohd-a** [comment]
Fixed: [#646aefa](https://github.com/hussainmohd-a/rethink-app/commit/646aefa7d6f9c17fbecba02d801f26bd5597eb5c), will be part of v054b
