### ISSUE TITLE
v053i does not work with socks proxy

### ISSUE THREAD

**Issue by nahuhh** [celzero/rethink-app#531]
On the previous version, I could setup dns = 127.0.0.1:5400 (tor dns) and setup socks5 proxy = 127.0.0.1:9050

_Only_ since the update, tor connections fail / the socks proxy doesn't seem to forward correctly.

**Comment by ignoramous** [comment]
You're right. I did test SOCKS5 with v053i before release and it worked then. I tried a bunch of things today, and SOCKS5 isn't working at all.

Looking into it the first thing tomorrow. Thanks for the bug report.

**Comment by ignoramous** [comment]
Took longer than expected. We switch to using `io.Copy(dst, src)` ([commit](https://github.com/celzero/firestack/commit/928af385c795aaeb6c83c4f4653a4c3b1332833f#diff-c449cc29c2dfbf1f83c025bc6382969ef2838f20ad4a00f4e843d3a38555c6bd)) for TCP proxying. This has broken the chaining between SOCKS5 endpoint and Rethink.

That's because the SOCKS5 API does not implement a `io.Reader` / `io.Writer` interface to make `io.Copy` work. Silly (but an expensive) mistake. I intend to fix this and release a build by Sunday (provided no other dire issue crops up in testing).

**Comment by ignoramous** [comment]
Fix commited (now using a different SOCKS5 client): https://github.com/celzero/firestack/commit/34ee72663ae2a5927f0a570861aa232427354aca

Not yet released.
