### ISSUE TITLE
[Firewall Enhancement]: netstat alike funcionality (firewall blind to connections?)

### ISSUE THREAD

**Issue by Horizonbli** [celzero/rethink-app#544]
Hello,

I recently started using Termux, and while playing around with netstat I found that the security apps I am running at the moment seem to be blind to connections established to *.1e100.net. Actually what's seen are IPs, but pinging them back reveals the hostnames.

I figured out what was happening, and the problem was I switched mobile cards. I forgot to set the APN proxy and port to my likings.
That solved it.

Can RDNS be made to spot these connections, just as or even better?? than netstat? If so (why not???), it would be more than welcome.

What do you think?

Thanks!

Edit: I mentioned firewall because that's what made sense. You folks know it better, so if possible to implement such functionality, but not through the firewall, perhaps changing title would be better.....

**Comment by ignoramous** [comment]
Hi, thanks for your bug report (:

> Can RDNS be made to spot these connections, just as or even better??

Those connections to `1e100.net` are to Google servers (see [`whois`](https://archive.is/OFAkD)). I'm guessing those are connectivity checks, which always happen outside of the VPN. See [this tweet by GrapheneOS](https://twitter.com/GrapheneOS/status/1580186268759363584) / [mirror](https://archive.is/xYZ9x).

> just as or even better?? than netstat? If so (why not???)

If I'm not mistaken, I don't think Rethink can capture that traffic. Perhaps, I can only think of Afwall+ being capable enough to do so, since it amply uses `root` privileges to control connectivity.

If you're on Android 9+, you can try running Rethink in VPN Lockdown mode (enable *Block connections without VPN* from Android VPN Settings, [ref](https://archive.is/y98XR)). I wouldn't be surprised even if that leaks connections that Rethink can't see ([see](https://archive.is/CrzTE)).

----

I'm inclined to close this issue unless you disagree with the assement above that the connections to Google servers could have been connectivity checks or just some System Apps bypassing the VPN altogether, which they can whether or not *Allow bypass* (#33) is enabled (#224).

**Comment by ignoramous** [comment]
#224 also see: https://issuetracker.google.com/issues/250529027

Closing per above... Reopen if you think I've misunderstood the ask. Thanks (:
