### ISSUE TITLE
Test on Android 6

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#563]
A user complained that v053i onwards, the app won't install on Android 6.

Test this.

**Comment by hussainmohd-a** [comment]
Crashes that are seen on Android 6 devices are caused by dependencies using Java 8+ APIs. To fix this we need to enable the desugaring support for the app.

Reference: https://developer.android.com/studio/write/java8-support

Fix: #[7e1f](https://github.com/hussainmohd-a/rethink-app/commit/7e1f092c6e51d4f82d1de8b1247823b0cca515c1)
