### ISSUE TITLE
Cannot enter DNS Configure and Logs tabs / pages after first run

### ISSUE THREAD

**Issue by TissuePowder** [celzero/rethink-app#605]
Version: v053k (fdroid)
OS: Android 12

I suppose I should be able to enter the DNS `configure` and `log` pages any time I tap on the blue `DNS` or `DNS logs` button on front page. But I can't. I was only able to enter that page after installing the app for the first time. After that, every time I try to access that page, I get a small "Private DNS has been set" message pop-up, and nothing else.

![Screenshot_2022_10_24__02-16-51](https://user-images.githubusercontent.com/39616942/197416157-189d9e70-7b46-4300-8bc5-6e8e6793844a.png)

After a number of tries I found out I can enter that page after turning off my phone's internet connection. But this shouldn't be necessary. I should be able to enter the page any time I want.

**Comment by ignoramous** [comment]
This is expected behaviour. If *Private DNS* is enabled, then there's no use for DNS functionality of the Rethink app. Btw, none of the settings in Rethink's DNS pages is going to be *effective*. In fact, it is a source of many a confusion.

I think *Private DNS* may not be active when there's no network might be why the DNS page is accessible.

The only way to access Rethink's DNS page is to disable *Private DNS* ([how](https://archive.is/lVMkZ)).

**Comment by TissuePowder** [comment]
Oh I see now, my apologies. My private dns was set to automatic. Though, since it raised a confusion, what would you think about the idea of providing a bit of hint to turn off private dns in android system settings, or maybe showing some more information when a user is trying to access that app feature?

**Comment by ignoramous** [comment]
> what would you think about the idea of providing a bit of hint to turn off private dns in android system settings, or maybe showing some more information when a user is trying to access that app feature?

Makes sense.

I believe "Private DNS has been set."  doesn't really hammer home the point that having so means no control over DNS from within the app.

Will attempt to create a different UI around this, in the upcoming release, `v053L`.
