### ISSUE TITLE
SOCKS5 app selection likely broken

### ISSUE THREAD

**Issue by ignoramous** [celzero/rethink-app#608]
In a screen grab a user shared, it appears that no matter which app (in this case, `Psiphon`) they select from the SOCKS5 proxy dialog, the selection reverts back to another app (here, `termux`).

https://user-images.githubusercontent.com/852289/198072342-aa6e5c82-23f5-451c-a57d-0b111439e6c6.mp4

**Comment by Tatasky956** [comment]
When try to set socks proxy. The app exclude from list and port revert back to previous app. Setting not change to new settings. Pls fix it.ty

**Comment by ignoramous** [comment]
The issue here is with the UI showing incorrect value. The chosen app in fact is what's used by Rethink underneath.

**Comment by hussainmohd-a** [comment]
Instead of fetching the current configured app on SOCKS5 configure dialog, the UI was showing the 
previously configured app. But the underlying SOCKS5 implementation was fetching the right value. 

Fixed the UI behavior in https://github.com/hussainmohd-a/rethink-app/commit/828b55b954e9c2b896be5c49658d99c45bcb33e1
