### ISSUE TITLE
Dns configuration resetes randomly

### ISSUE THREAD

**Issue by zabi94** [celzero/rethink-app#632]
RDNS performs poorly for me, and I want to configure adguard in my dns settings.

When I do that, the setting is saved for a couple hours before resetting automatically to rdns.

V053k, android 12, motorola edge 30 pro, update S3SH32.12-41-2

**Comment by ignoramous** [comment]
> When I do that, the setting is saved for a couple hours before resetting automatically to rdns.

Are you using DNSCrypt? If so, wait for `v055` when we plan to "relax" our rather strict DNSCrypt impl a little bit (to match upstream's): https://github.com/celzero/firestack/issues/4

**Comment by zabi94** [comment]
Yes, I use dnscrypt

**Comment by ignoramous** [comment]
> Yes, I use dnscrypt

The app fallsback to RDNS when it cannot refresh DNSCrypt certs (which it does so periodically once every 2 hours or so IIRC).

See #211 where we intend to let the user decide on the fallback DNS to use (instead of defaulting to RDNS).

As for DNSCrypt improvements, see the bug linked to above.

Intend to close this issue as its redundant given other open issues (linked above).
