### ISSUE TITLE
Blocking mobile also blocks on wifi

### ISSUE THREAD

**Issue by astroxe** [celzero/rethink-app#713]
On my phone, apps which are `blocked on metered (mobile)`, but not on wifi, can't connect even on wifi. It has Android 7.1.1 from Samsung.

**Comment by ignoramous** [comment]
Hi: I'm unable to reproduce the problem you're seeing.

Can you share a screen recording, please? If you cannot upload it here, send it over [telegram](https://t.me/aliakbarmurtaza) or peertube / youtube?

Also are you on the *latest* version, `v053l`? You can look for version at the bottom of Rethink's *About* screen.

**Comment by ignoramous** [comment]
Just in case: Make sure the logs you're looking at aren't *older* logs from a time when the connection was genuinely blocked because the app tried connecting over a metered network.

**Comment by astroxe** [comment]
Hello, I am using the f-droid version `v053l`. I'm not sure what should be recorded in particular:
- When the device has wifi on and mobile off, Rethink's wifi setting is ignored, the mobile setting has effect
  - Blue mobile icon allows internet and the log's app sheet says `No Rule` in green
  - Red mobile icon breaks internet and the log's app sheet says `Metered (Mobile)` in red
- When the device has mobile on and wifi off, Rethink's wifi setting is ignored, the mobile setting has effect

The phone is Samsung Galaxy J5 (2016).

**Comment by ignoramous** [comment]
Hi: Thanks for getting back.

Recording of your screen showing what you're describing, showing app firewall rules and corresponding network logs.

I ask because, it is hard to understand the scenario you're trying to portray.

Btw, is the Wifi connection you're on a _metered_ connection (metered connections are typically expensive networks where you pay high per-GB cost like public WiFi networks and Mobile LTE/4G/3G networks)?

**Comment by ignoramous** [comment]
Hi: In `v053n` ([released on 13 Jan 2023](https://rethinkdns.com/download)), the bottom-sheet that crops up when you tap on the down-arrow next to the `START` / `STOP` buttons on Rethink app's homescreen will now show if the *active* network is "metered" or "unmetered". Some WiFis are marked "metered", which means, if an app that one intends to block for "mobile" ("metered") would also get blocked when connected to such WiFis. Commit: https://github.com/celzero/rethink-app/commit/9fd2655c45bf1344f43d66d6ed9c547a7ef9bc7c

Armed with this new capability, please let us know if the behaviour you're seeing is on a "metered" WiFi network or not. Because, if not, then there's a grave bug with Rethink. Re-open this issue if that's the case. Thanks.

**Comment by ignoramous** [comment]
<details>
<summary>
Screenshot of the bottom sheet showing "metered" as the *active* network is indeed a "metered" mobile network.
</summary>
Notice the unblurred part right at th bottom of the screen
![Screenshot_2023-01-13-00-10-59-04_c8cbde12d3521911922be4eee6a05664-01](https://user-images.githubusercontent.com/852289/212153145-679dc87e-f9be-4da1-b110-b7379babd1d1.jpeg)
</details>

**Comment by astroxe** [comment]
So the issue was that the system setting `Connections` - `Data usage` - `Restrict networks` was enabled. Now the connection shows up as `Unmetered` and apps are blocked / not blocked as expected. Thank you for looking into it! The new bottom sheet label saved me quite some time while playing around in the settings.
