### ISSUE TITLE
Weather.com

### ISSUE THREAD

**Issue by retroluv** [celzero/rethink-app#716]
Somehow it appears that the StevenBlack (master) list interferes browsing the weather.com radar section, but when I look and search I cannot find mparticle.weather.com in the list. Disabling it restores proper browsing.

**Comment by ignoramous** [comment]
Hi, `mparticle.weather.com` isn't blocked by any of the blocklists Rethink supports (blocklists last updated on 8th Dec): https://rethinkdns.com/search?q=mparticle.weather.com

Can you check if you're on the latest blocklists (if you're using on-device)? If not, what version of the app are you on? `v053l` is the latest, which is what you should use.

**Comment by retroluv** [comment]
Hi:

I'm on the latest on both, sorry yesterday I couldn't post the following attachment on android, but today logged on PC...
![1](https://user-images.githubusercontent.com/120674105/208168514-b1bd9f3e-bd12-4b1b-982d-a53e73146e08.jpg)
BTW, I wanna thank you devs & contributors for the development of this kind of android firewall without root being able to block or allow individual IPs. Hopefully the feature to ignore individual domains is up soon. :)

**Comment by ignoramous** [comment]
Ah, i just checked on my Android and yes, almost all lists block `mparticle.weather.com` because it `CNAME`s to `mparticle.map.fastly.net`. Rethink does what's known as *uncloaking* (a term for figuring out if one dns name is pointing to another dns name), and blocks accordingly.

https://rethinkdns.com/search?q=mparticle.map.fastly.net

This isn't a bug ;)

---

Thanks for your praise. We try. We are slow. But we are also at our limits. This stuff is hard.

As for ability to allowlist / denylist individual domains, that's coming. Soon. The work on it is paused for the time being as the lead developer on Rethink app is busy with another important task. But I expect him to pickup work on allowlist / denylist immediately, and probably ship it by the turn of the year, if not sooner.

**Comment by retroluv** [comment]
Thank you for the explanation, it makes sense now.

Regards!

**Comment by ignoramous** [comment]
> Thank you for the explanation, it makes sense now.

The search webpage now shows if a website was blocked due to `CNAME` / `HTTPS` / `SVCB` uncloaking: `mparicle.weather.net` should now show results for its `CNAME` -> `mparticle.map.fastly.net` too ([ref](https://rethinkdns.com/search?q=mparticle.weather.com)) (:
