### ISSUE TITLE
rethinkdns + tif hagezi filter

### ISSUE THREAD

**Issue by unknown4849** [celzero/rethink-app#731]
i use hagezi threat filter but some strange happend.
`discord-attachments-uploads-prd.storage.googleapis.com` got blocked by the filter.
i search on the filter maybe some of domain got blocked but not found who make this problem, but i try adguard app with this filter and working fine i can upload to discord , but use Rethinkdns this problem still happend

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/74445408/210480972-9ac8ed76-5c9c-4424-9755-7d11c9b7bc21.png)

![image](https://user-images.githubusercontent.com/74445408/210480976-e3c49814-2151-4067-831b-39dd36f558cf.png)
</details>

**Comment by unknown4849** [comment]
> What version of the blocklist do you use? The latest is from 1st Jan, 2022.

latest v23.01 (02)

**Comment by ignoramous** [comment]
https://rethinkdns.com/search?q=discord-attachments-uploads-prd.storage.googleapis.com

Threats (Hagezi), Threats (embreaj), Ads (The Blocklist Project) may be blocking it?

**Comment by unknown4849** [comment]
> Threats (Hagezi)

but strange is this domain `storage.googleapis.com` not blocked by the filter
![image](https://user-images.githubusercontent.com/74445408/210829724-a3d29395-4d84-4bb5-8261-5fca629380f2.png)

like i say before i already search what domain make this problem and found nothing,

**Comment by ignoramous** [comment]
Ah gotcha. On RethinkDNS, some lists are augmented with other lists. Hagezi, for instance, is augmented with MyPDNS.org's Phishing and Marco Acorte's AntiSpam: https://github.com/serverless-dns/blocklists/blob/f308a21d89871aeff427e98c378d5a4a9354314b/config.json#L642-652

I'll add a label to such augmented lists so that folks aren't confused by the behaviour they see on RethinkDNS.

---

As to why we augment certain lists, it is mostly to ensure "coverage" of lists we mark as level 2 (the lists with most extreme form of blocking). Threats (Hagezi) is a "level 2" list.

**Comment by ignoramous** [comment]
We've removed other lists from `Threats (Hagezi)` ([pr](https://github.com/serverless-dns/blocklists/commit/85e66899ee791a59672f46a1f085212db4e7bafa#diff-587cb980af76fdc7e52369fd0b9d926dff266976b6f8ac631e358fecc49ff8cfR636)).

Thanks for your bug report (:
