### ISSUE TITLE
Latest update broke everything

### ISSUE THREAD

**Issue by tlartaud** [celzero/rethink-app#750]
Hi there,

Thanks a lot for your app, it's being very useful.

However, I'm a bit mad about the latest update since th changes simply broke everything.

I was using the global firewall setting block everything except app & IP with exeptions.

The problem is that you changed the menu to allow IP.

I can now only see "Trust" or "Block", which makes clearly no differrence when this global is activated. It means that all the IPs I had previously whitelisted by selecting the option "bypass app rules" are no more working. Everything is now being blocked.

Could you fix or explain what's the workaround would be? I'd like to still use that global option but it looks like you forgot to handle the use case where users prefered to block ererything at first, and then managed apps one-by-one, and IPs one-by-one, by adding them to an exception list.

Thanks by advance for your assistance.

Regards.

**Comment by tlartaud** [comment]
What's strange is that your code shows that I should see a "bypass" option in the dropdown: https://github.com/celzero/rethink-app/blob/v0.5.3n/app/src/main/java/com/celzero/bravedns/service/IpRulesManager.kt#L98

After the update, I can only see "no rule", "block", or "trust"...
The "bypass" option simply disappeared.

Is there anything we should do after updating? Like clearing the cache or something?

**Comment by tlartaud** [comment]
Up: It looks like we now need to set an app as isolated to let the bypassed IPs to be taken in account: https://github.com/celzero/rethink-app/blob/56b9bc8ed433608e78d97b66f5dbe5f934bbe0b8/app/src/main/java/com/celzero/bravedns/service/BraveVPNService.kt#L346
I guess that change should be documented xD

But my question is: does an isolated app would also bypass the DNS? Hope not :)
Thank you by advance.

**Comment by ignoramous** [comment]
> Could you fix or explain what's the workaround would be? 

The alternative is to go to "Apps" screen and tap on the "Isolate" icon and put every listed app in isolation / sandbox.

In case you install new apps, make sure to turn on *Block newly installed apps* to make sure they don't connect without your explicit approval.

> I'd like to still use that global option

You can still leave this option turned ON. It behaves a bit differently now. As in, only apps that are in *Bypass Universal* list or IPs in *Bypass Universal* list will be allowed, in addition to *Trusted* IPs for apps in *Isolation* mode. I know this is a bit confusing, but I swear it makes the most sense when you consider other possibilities.

> I can now only see "Trust" or "Block", which makes clearly no differrence when this global is activated.

Like you yourself found out, simply put all apps in *Isolate* mode and you should see *Trusted* IPs being let through.

Btw, the rules should been migrated. Did you lose any of the previously set *Bypass App Rules* IPs?

> However, I'm a bit mad about the latest update since th changes simply broke everything.

Sorry but things will likely keep changing until we hit v1. Hopefully not in a very drastic way. The only respite is because we develop in the *open*, you're free to monitor for changes and alert us in case we  do something stupid, like you did here :)

> But my question is: does an isolated app would also bypass the DNS?

It does not bypass DNS blocks.

**Comment by tlartaud** [comment]
@ignoramous Thanks a lot for that reply! Really appreciated!

I now better understand the "isolate" mode.

> alert us in case we do something stupid
This is not stupid at all. This app is far away from being stupid. Honestly, that's the best one I've found doing that job for now. But I must admit that this update was pretty confusing. Maybe could you enhance the descriptions behind the "?" buttons to describe more precisely the differrences between each mode? Especially for the fact we need to set an app to "isolate" mode in order to be able to use the exception IPs lists?

Also, maybe I'm wrong, but after the update, rDNS+ wasn't active anymore and a DNS test told me my DNS were being leaked. Not sure why, maybe an incorrect manipulation from me.

> Did you lose any of the previously set Bypass App Rules IPs?
No, the list kept intact, and turning the apps I wanted to monitor to "isolated" mode fixed the issue.
The good thing I noticed is that the WIFI/DATA block buttons under apps settings now work as expected, if the global setting is activated (it has no effect before the update).

I hope I'll be able to contribute in any way in the near future. Really great app! Keep it going!

Regards.

**Comment by ignoramous** [comment]
> Maybe could you enhance the descriptions behind the "?" buttons 

The app has poor UX. May be we'll improve once we have some breathing room. We're working on just too many other app-related important things.

> Also, maybe I'm wrong, but after the update, rDNS+ wasn't active anymore and a DNS test told me my DNS were being leaked. 

No leaks as far as  I am aware. And if you're using a service like DNSLeakTest, you must know that those aren't built to detect leaks from apps like Rethink that use encrypted DNS (DoH) but for plain old DNS. From [their FAQ](https://archive.is/fwg9z): `Under certain conditions, even when connected to the anonymity network, the operating system will continue to use its default DNS servers instead of the anonymous DNS servers assigned to your computer by the anonymity network. DNS leaks are a major privacy threat since the anonymity network may be providing a false sense of security while private data is leaking.`

>  The good thing I noticed is that the WIFI/DATA block buttons under apps settings now work as expected, if the global setting is activated (it has no effect before the update).

Heh, yeah there was one edge case where this wouldn't have worked in the previous release... which is one among the reasons we released `v053m` within a month of `v053l`.

> I hope I'll be able to contribute in any way in the near future. Really great app! Keep it going!

Thanks. I am sure similar apps will be released in the coming months; I hear a couple other dev teams working on it. So, you'll have plenty options going forward (:
