### ISSUE TITLE
What Rethink DNS should improve compare to Adguard android

### ISSUE THREAD

**Issue by lessload** [celzero/rethink-app#779]
Rethink DNS
- user cannot add host list for dns like in Adguard ( it not accept by play store?, can be seperated in two version?)
- - Not have ability to edit ip in ip rule. Not have ability to edit rule like text edit mode in Adguard.
- IP Rule useles in many case. App should have something  like auto allow/block ip base on domains name or rule by domains name. (and auto delete/add when ip resolve of domain was changed.)
- not understand how IP rule order (Which rule was apply first?).  If i want to block 10.0.0.0/24 but allow 10.0.0.16, how?
- flag is beautify but not every one can remember which flag is whice county. use country code or flag with country code should be better. 
 - `Network log for this app` not show all ip compare to `Network Logs`
 - use Dnscrypt but it always switch back to RethinkDNS not sure why ? should have some option like `skip dnscrypt connection test` ?
 - IP Rule not support Port range like port 1080-1090

**Comment by ignoramous** [comment]
Thanks for your feedback. It is useful.

> user cannot add host list for dns like in Adguard ( it not accept by play store?, can be seperated in two version?)

Plan to implement this, but not a priority given other pressing issues and features, see #237 

> Not have ability to edit ip in ip rule.

Edit isn't supported because the rules are cached. For now, you have to delete an existing entry and add a new one. Tracking *edit rules* feature this here: #782

> App should have something like auto allow/block ip base on domains name or rule by domains name.

This is coming in the next version, `v054`, due in a day or so: https://twitter.com/rethinkdns/status/1623146552683540480

> not understand how IP rule order (Which rule was apply first?). If i want to block 10.0.0.0/24 but allow 10.0.0.16, how?

The behaviour when there are conflicting rules is "undefined". We must address this soon! #781

> use country code or flag with country code should be better.

May be. But the logs UI is already too cluttered to any show extra information.

> Network log for this app not show all ip compare to Network Logs

Not sure what this means, but network logs shows a real-time chronological log of network connections. App specific screen isn't for that.

To view an app-specific chronologically ordered logs, simply type the app's name in the search bar in the network logs UI.

> use Dnscrypt but it always switch back to RethinkDNS not sure why ? should have some option like skip dnscrypt connection test?

This has been fixed in the next version, `v054`, due in a day or two.

> IP Rule not support Port range like port 1080-1090

Unimplemented, tracking here: #780

**Comment by lessload** [comment]
v053
- i think is not a good idea to remove firewall rule after remove app beacause 
    1. if i accidentally remove some app i will lost the rule of that app. it should have sepperate section to manage rule ,that app not install.
    2. if i export rule to another mobile i need to re-config all app that i didn't install ?

**Comment by lessload** [comment]
the same weird bug same as Adguard app.
- example: when i click like `bit.ly/xxx` link in `Facebook` app and it open `bit.ly/xxx` in webview but not load because it block by isolate mode and i click open the link in others web browser `bit.ly/xxx` strat open on `Firefox` but loading fail. I have check in log it show as `bit.ly` try to load by `Facebook` not `Firefox`. Not understand why ? it happen sometime not always.
 
Adguard have exactly same bug.

**Comment by ignoramous** [comment]
>  i accidentally remove some app i will lost the rule of that app. it should have sepperate section to manage rule ,that app not install.

We have considered this, but it isn't trivial to build this feature, as in, retain rules across app re-installs. Too many edge cases to handle.

> if i export rule to another mobile i need to re-config all app that i didn't install ?

Yet to support such a scenario; see #757 

>  have check in log it show as bit.ly try to load by Facebook not Firefox. Not understand why ? it happen sometime not always.

Is `bit.ly` blocked at the DNS too? Could be the DNS cache getting in the way... Other than, it is hard to tell what's going on. All I can say is, one app's IP / firewall rules shouldn't affect another app's.

**Comment by ignoramous** [comment]
Let me know if there are more inputs or feel free to reopen this bug. Most of the unimplemented stuff have been split into its own issues. Closing...

Thanks (:
