### ISSUE TITLE
Proxy mode as alternative to VPN mode

### ISSUE THREAD

**Issue by serrq** [celzero/rethink-app#790]
I already have a Wireguard active VPN on my phone. But unfortunately I cannot use Rethink for DNS + Firewall because it can't run itself as VPN service due the presence of Mullvad.

Might you develop an alternative Proxy mode in order to solve this issue and allow coexistence among different services?

**Comment by ignoramous** [comment]
Yep, planned (give it a month or so, but also know that I've been saying this for well over 2 years now ;) We got it working but then WireGuard changed. So, we got it working again. But then, our network engine changed. And then, WireGuard changed some more, and our code got refactored wholesale... so here we are, with a feature that's been complete since a year but never released.

Might happen soon, as that's my sole focus for this month.

Dup #52
