### ISSUE TITLE
Blocked domains shown as Allowed in DNS Logs

### ISSUE THREAD

**Issue by MetaApo13** [celzero/rethink-app#829]
**Description**
I noticed that domains that are DNS blocked cannot be identified as blocked. They appear in the allowed domains filtered list. However, these domains show up in the Network logs as being blocked (either 'DNS-blocked' or due to a user set rule). This inconsistency started appearing some time after updating the app to v0.5.4a. 
The issue results in a certain degree of confusion as to whether the domain has been blocked or allowed.

**Expected Behaviour**
The DNS logs generally show domains that are blocked due to rules in DNS blocklists with a red line in front. The blocked filter can also be used to see all blocked domains

**Screenshots**

![c2700512-b03b-426d-b307-cc0138faa796](https://user-images.githubusercontent.com/92925504/224481469-3dae4f39-c19d-49b1-866e-eada49cf9d50.png)
![Screenshot_20230311-163809-214](https://user-images.githubusercontent.com/92925504/224481483-328a6f12-a300-4aac-973d-e4e736e82a15.png)

**Comment by ignoramous** [comment]
Thanks. This is expected behaviour if there any per-app domain (allow/block) rules set. Per-app domain rules can only be applied at the network connection time.

The UI is making this too obvious, but perhaps we could convey this information a bit better.

Closing as dup of https://github.com/celzero/rethink-app/issues/817

(if incorrectly closed, feel free to reopen).
