### ISSUE TITLE
Filtering by Blocked the DNS Log page makes the app crash

### ISSUE THREAD

**Issue by signed-log** [celzero/rethink-app#852]
Device : Oppo Find X5 Pro (Global), ColorOS 13.0 (Feb patch), Rethink `0.54a` downloaded from releases

Step to reproduce :

- Open the app
- Go into DNS Logs
- Fliter to only display blocked entries

Page is blank and the app then proceeds to crash

![Screenshot_2023-04-04-17-51-17-30_c8cbde12d3521911922be4eee6a05664.jpg](https://user-images.githubusercontent.com/14251971/229849384-247609e5-60c3-41b6-9492-12f356a0b07c.jpg)

**Comment by hussainmohd-a** [comment]
Thank you for reporting the issue. We are already working on it, and you can track the progress in issue https://github.com/celzero/rethink-app/issues/793. Additionally, could you please let us know the number of entries on the DNS logs screen? You can find this information on the Home screen, where it will say "X queries".

**Comment by signed-log** [comment]
Sure

```
446K connections
207K queries
```

**Comment by ignoramous** [comment]
In `v054c` ([f-droid](https://f-droid.org/packages/com.celzero.bravedns/), [play](https://play.google.com/store/apps/details?id=com.celzero.bravedns)), we've fixed the indices on the logs tables ([commit](https://github.com/celzero/rethink-app/commit/6e1987c2b25443527a8c42bfcf5dad867e2cfd5c)) and limit just how many log entries the UI loads ([commit](https://github.com/celzero/rethink-app/commit/c03ca6a3d5a39f8ec04d65a88c0e95e45d6db6cb)). It should have *slightly* improved the odds of avoiding ANRs, but those won't completely go away (since 200K+ / 400K+ is one log entry too many for the UI to handle).

Can you please let us know if you still see crashes in `v054c`? Please re-open this bug in case they're *frequent*.

Related: We intend to implement sqlite's FTS4 (full-text search) to help with free-form *text-based* filters in tables with 100K+ entries in `v055b`: #847. Sharding and roll-ups are the two long term solutions we have in mind for such large tables, but they aren't that simple to implement; so unsure if we ever do it, as not many folks hit 100K+ entries (logs are maintained for a running 7-day period: #827).
