### ISSUE TITLE
not compressed apk

### ISSUE THREAD

**Issue by zedd-0** [celzero/rethink-app#857]
hi.

if i do zip your apk (~46MB), by using winrar (zip, fastest)
i do get a ~21MB file.

is your file uncompressed?
even with the fastest preset?
please compress your file.
reaching half the size should be an argument.

thx.

**Comment by ignoramous** [comment]
Compression (of libs) is not recommended since Android would have to maintain both compressed and decompressed copy of the APK (on the device) post installation: https://developer.android.com/topic/performance/reduce-apk-size#extract-false

Note that the downloads from Play are gzipped compressed, anyway.

Rethink cannot sue *Android App Bundles* (I don't think) because we sign our own APKs (and don't leave it upto Google). What we could do is publish *lean multi-APKs* but unsure if F-Droid supports it.

If I'm missing some critical compression technique that's applicable to, please feel free to reopen / suggest. Thanks.
