### ISSUE TITLE
Trust domains should be allowed by the Firewall regardless of upstream 

### ISSUE THREAD

**Issue by michael1900** [celzero/rethink-app#874]
Hey Celzero, is it possible to add a whitelist in DNS section like on adguard app? 
Or, in next paid account, there will be a section with option to whitelist sites like on NextDNS for example?

I mean, sometimes i have the need the whitelist a site from the filter list and this feature will be great!

**Comment by ignoramous** [comment]
Whitelisting is named *Trust* in Rethink; a feature available since [`v054`](https://rethinkdns.com/download) (released in March). Do you not find that rule? Tap on any domain entry in the *DNS Log* UI, and you should see a drop-down (in the bottom-sheet that comes up) from where you must be able to *trust* (whitelist / allowlist) the domain.

You can also *Trust* any domain per-app, too.

**Comment by 0xlne** [comment]
This was working in v0.54a but not anymore in v0.54b. Details/screenshots were posted on Telegram.

**Comment by ignoramous** [comment]
*Trust*ing domains works best with Rethink but there's no reason it shouldn't continue to work with other upstreams in a "degraded" mode.

**Comment by Artim96** [comment]
> _Trust_ing domains works best with Rethink but there's no reason it shouldn't continue to work with other upstreams in a "degraded" mode.

That's also my problem. It should work with any DNS service, I don't see why it shouldn't, yet I just noticed that trusted domains still get blocked on 54c. I mean after all, it should all be happening on device, if a domain is trusted, simply pass it through to the set DNS server and ignore any mentioning if any of the selected block lists.

**Comment by ignoramous** [comment]
> It should work with any DNS service, I don't see why it shouldn't, yet I just noticed that trusted domains still get blocked on 54c. 

True.

The reason we support *Trust*ed domains with rdns+ (*remote blocking*) is because the same resolver origin can change its *block* (deny) / *trust* (allow) behaviour depending on the URL path; for example:  `https://sky.rethinkdns.com/` *block*s nothing (*trust*s everything) while `https://sky.rethinkdns.com/rec` *block*s ads and trackers. This behaviour isn't possible to implement with other upstreams.

As for *On-device blocklists* (which is nothing but rdns+ running *locally* on-device), these should be bypassed for *trust*ed domains where applicable. It should be a straightforward thing to do so (after some of the [recent](https://github.com/celzero/firestack/commit/7047de0248dfe4aadd9240b69405054f2ae3ee7a) [changes](https://github.com/celzero/firestack/commit/db3fca2457b068bcf5b39762f4737a6433906bfc)). Expect it to land in the upcoming version, `v055` (final week of May).

**Comment by hussainmohd-a** [comment]
Furthermore, there was a bug present in v054c. When users trusted the app using the edit option, the associated lists were being ignored, despite the UI indicating they were trusted. This issue has been addressed and resolved in v055 with an appropriate fix. 17e8c288

**Comment by hussainmohd-a** [comment]
The issue has been fixed and released in version v055.
