### ISSUE TITLE
[bug] Cannot update on-device blocklists in v053b

### ISSUE THREAD

**Issue by PoneyClairDeLune** [celzero/rethink-app#875]
![IMG_20230502_182403_047](https://user-images.githubusercontent.com/88174309/235753295-9389509e-6206-4481-8a5d-888b8901a937.jpg)

https://t.me/rethinkdns/76328

https://t.me/rethinkdns/76352

https://t.me/rethinkdns/76392

Errors will always occur when trying to update the on-device blocklists with any possible mean.

**Comment by hussainmohd-a** [comment]
Ref: https://github.com/square/retrofit/issues/3751
https://stackoverflow.com/questions/76118721/r8-full-mode-throws-class-cast-exception-agp-8-0
https://stackoverflow.com/questions/76073318/upgrading-gradle-from-7-4-2-to-gradle-8-0-0-gives-error-on-release-app-java-la

**Comment by hussainmohd-a** [comment]
The issue is R8 obfuscation throws a `ClassCastException `when a custom `TypeAdapterFactory `is used with **_Retrofit_**. The issue is caused by the obfuscation process renaming the classes used in the `TypeAdapterFactory`, which causes the `ClassCastException`. The obfuscation process have affected the class names on release builds.

As suggested by the issue(https://github.com/square/retrofit/issues/3751), using `proguard` rule to keep the class names unchanged during obfuscation will solve the issue. Below are the rules added in `proguard-rules.pro`
```

# Keep generic signature of Call, Response (R8 full mode strips signatures from non-kept items).
-keep,allowobfuscation,allowshrinking interface retrofit2.Call
-keep,allowobfuscation,allowshrinking class retrofit2.Response

# With R8 full mode generic signatures are stripped for classes that are not
# kept. Suspend functions are wrapped in continuations where the type argument
# is used.
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
```
