### ISSUE TITLE
Samsung Phones, No automatic start-up

### ISSUE THREAD

**Issue by iulko** [celzero/rethink-app#893]
Rethink DNS reports disabled after rebooting any Samsung phones, all of them Android 13, enable at start-up enabled. I have to start it manually. All battery optimizations are disabled. Other apps, like Netguard start without problems. Using system DNS and Github version.

I get notification:
"Warning: Rethink has been deactivated"

And in the app under start button
"Not protected"

**Comment by Rhys-T** [comment]
This is a long shot, but are you by any chance combining Rethink with personalDNSfilter? (If not, please disregard the rest of this comment.)

I had the same problem with that combination (Samsung + Android 13 + pDNSf + Rethink). If I quickly opened the notifications after startup, I could see Rethink come up for a fraction of a second, then pop the 'deactivated' warning. I eventually tracked it to pDNSf, whose auto-start code seemed to call `VpnService.prepare(...)` even when it wasn't set to run in VPN mode - see IngoZenz/personaldnsfilter#264. There's a test build in that issue that seems to fix it (though installing it and keeping the data/config from the release version is a bit tricky since it has a different signature/certificate), so hopefully that fix will make it into a release soon.

**Comment by iulko** [comment]
I do not use personalDNSfiler, but maybe your problem can narrow down the bug.

**Comment by ignoramous** [comment]
>  "Warning: Rethink has been deactivated"

This means some other VPN app has kicked Rethink from the VPN slot. Enabling *Always-on VPN* should fix this. As for why it doesn't happen with NetGuard... not so sure.

**Comment by iulko** [comment]
This is happens with Always-on VPN enabled.

**Comment by ignoramous** [comment]
> This is happens 

You see "Warning: Rethink has been deactivated!" with and without *Always-on VPN* enabled, correct? That's strange. This behaviour you describe doesn't happen on the Androids we have, so I'll see if I can find a Samsung running Android13 to grab some logs.

**Comment by iulko** [comment]
Yes, when I boot the phone I get this notification whatever options I set, I even tried in Airplane mode etc
I'm using system dns.

**Comment by Rhys-T** [comment]
Just started having this happen on my Samsung tablet after installing the May 1, 2023 security update to the OS. I'm running Rethink v054c from F-Droid, which hadn't had this problem previously (as long as another VPN didn't kick it out).

**Comment by ignoramous** [comment]
Thanks. Unfortunately, we do not have a Samsung device to know why this happens. It is a peculiar behaviour that doesn't show itself on OnePlus and Xiaomi phones we have lying around. We'll keep looking. Hopefully, I can get a Samsung from one of my friends to test this.

**Comment by ignoramous** [comment]
Another user with Pixel 6 (Android 13) has raised a similar issue #905 which makes me think that this is somehow tied to Android 13 and changes made for `v054c`.

**Comment by ignoramous** [comment]
A user on Android 10 confirmed it happens on their ROM too. So it isn't limited to an Android version either. Strange that it doesn't happen on my Android (which is running v12).

We intend to fix whatever is causing this on priority.

**Comment by raven9nine** [comment]
This is not Samsung specific I see the same issue on a Moto phone Android v10.

**Comment by ignoramous** [comment]
Yep, we think we know what's up and have a fix ready to go. Hopefully, with `v055` (close to releasing it), this bug is fixed.

**Comment by hussainmohd-a** [comment]
https://github.com/hussainmohd-a/rethink-app/commit/0979b6363082c36cb032bc113c6f48f1cb3824c6 will fix this issue

**Comment by ignoramous** [comment]
Shipped in [`v055`](github.com/celzero/rethink-app/releases/tag/v0.5.5) (14 Aug).

Should show up on F-Droid and PlayStore by the end of this week.
