### ISSUE TITLE
VPN Lockdown with proxy

### ISSUE THREAD

**Issue by tzugen** [celzero/rethink-app#916]
Hi,
it seems it's not possible to actually force an app through Tor (or another proxy) without leaks.
When I don't activate lock down mode, the proxy seems to work. But sometimes the app will stop working and the traffic will just continue in clear.
But when I Enable lock down mode to prevent leakage, it also blocks tor.
my proposal would be that you if lock down is activated, rethink should simply pass on orbots connections

**Comment by ignoramous** [comment]
Hi there,

>  my proposal would be that you if lock down is activated, rethink should simply pass on orbots connections

This isn't possible. Rethink cannot route traffic to another app (like Orbot) when VPN is in *lockdown* mode. This is an Android limitation (and it makes sense if you think about it: *lockdown* means blocking all traffic except the one going out of Rethink... which means, any other app is unable to forward traffic to the Internet).

As for supporting remote proxies in *lockdown* mode, see: #892

**Comment by ignoramous** [comment]
I am not sure if I understand, but:

> but there should be away to ensure that data which is meant to be routed through the ~~proxy~~ VPN is actually doing that and not being leaked

Yeah, that's the guarantee that AOSP via `Block connections without VPN` gives. There cannot be any traffic leak (well, at least per documentation) outside of the VPN tunnel. There are no such guarantees for "proxies" from AOSP.

> Otherwise you can not really rely on it for privacy purposes, and this is what is rethinks "selling" point, no?

Rethink doesn't leak connection per my knowledge, but no one has done a security review... With `Block connections without VPN`, Rethink cannot forward traffic to any other app / proxy running on the device. It can, however, forward it to a remote proxy, but that's yet unimplemented: #892

And regarding, privacy, there's just too many things Rethink cannot do (it is an installed app with very limited privileges, if any). One might think, `root`ing the device might give more control over privacy, but to me, that's a foot-gun to comfortable to carry around forever. Flashing ROMs don't help much either, since at the end of the day, the firmware and the hardware are all opaque blobs in the ODM's / OEM's control (who, in the past, have been caught running an entire kernel  / operating system alongside Android). It all depends on the threat model, I guess, depending on which Rethink is either snake oil or worth a $1000 bucks (:

**Comment by tzugen** [comment]
Hi :) Thanks for your long reply!

I think what I tried to ask for is actually pretty much #892 , but I am a bit confused that you describe it as "Rethink can, however, forward it to a remote proxy, but that's yet unimplemented" while in the bug its about the complete opposite: "However, even with "Block connections without VPN" enabled, some local host interfaces (i.e. lo, tunX) are still reachable and can be bound by a SOCKS5 proxy*." 

And I just tried with Netguard as well: I can setup Tor as Socks5 proxy, put the VPN in lockdown mode and add Orbot to the "allow in Lockdown" exception list and the logs show that there is traffic flowing between Netguard and Orbot. 
It doesn't really work though, since Netguard is missing a setting for split proxies and will just route all traffic from orbot trhough orbot again, creating a loop.

**Comment by ignoramous** [comment]
Apologies for long replies (:

Networking on Android is a bit confusing for everyone (including developers like me). We may also be wrong in our assumptions (see: the number of IPv4 / IPv6 and other network related bugs unresolved for months if not years).

> it doesn't really work though, since Netguard is missing a setting for split proxies and will just route all traffic from orbot trhough orbot again, creating a loop.

Yes, this is the problem. Android won't let any app create "split proxy" like you call it (or, network namespaces #393) to avoid that loop if `Block connections without VPN` is enabled. This is expected since Android treats the connections flowing to another app or proxy on device as *leaks*.

> However, even with "Block connections without VPN" enabled, some local host interfaces (i.e. lo, tunX) are still reachable and can be bound by a SOCKS5 proxy

Not sure what this comment means, but app cannot bind to *any* interface when `Block connections without VPN` is enabled, they're all bound to the `tun` device, and forcefully so. If any app is able to, then that's a security issue and should be reported to AOSP.

**Comment by ignoramous** [comment]
> Android won't let any app create "split proxy" like you call it (or, network namespaces https://github.com/celzero/rethink-app/issues/393) to avoid that loop if Block connections without VPN is enabled

#393 is now working in our experimental setup. Long way from making it work for all use-cases.
