### ISSUE TITLE
recommned to use hash of app name instead of  no_package_<uid>

### ISSUE THREAD

**Issue by lessload** [celzero/rethink-app#974]
i found `DNS` not have packageName and show as `no_package_1052` , it not good for long term development.
i recommend you to use hash of app name (DNS) to prevent duplicate rule conflicts when export/import to new device.

**Comment by ignoramous** [comment]
Hi there: Is this implementation detail you want changed or `no_package_<uid>` is something you see in the UI?

**Comment by lessload** [comment]
i saw in exported .db

**Comment by ignoramous** [comment]
System "packages" (UID 1052 for example) have immutable identities and remain the same on all Androids (of the same version).

In light of that, the concern you raise still hold? I don't think it does, but may be I'm not understanding your points properly.

**Comment by lessload** [comment]
> immutable identities and remain the same on all Androids

This is conmpletely wrong. from i saw uid from different brand, The same app name use different uid.
If your code variable rely on uid it will make backup/restore useless.

**Comment by ignoramous** [comment]
> This is conmpletely wrong. from i saw uid from different brand, The same app name use different uid.

System Components pretty much have UIDs set in stone; ref this file: https://archive.is/58SDu

Installed apps of course have varying UIDs from device to device.

> If your code variable rely on uid it will make backup/restore useless.

Rethink relies on UIDs to make firewall decisions. *Backup and restore* came much later on. And yes, we want to make *Backup and restore* work with package names instead of UIDs: #757

**Comment by ignoramous** [comment]
While this suggestion is valid, package names themselves could be considered unique enough. App names however needn't be unique (as in, multiple apps could be named "Calculator" or "Gallery" for example) and grabbing of hash of a app name isn't going to help us in any materialistic way, I don't think. Closing...

If anyone reckons this bug was closed prematurely or on error, please feel free to reopen.

**Comment by 0xlne** [comment]
Both of you are right.
Android system packages have immutable UIDs, but user-installed packages have changing UIDs.
Backup/restore in my opinion should rely on a consistent method, also for the sake of simplicity, & in my opinion, the only reliable way to do this, is to use package names. Not app names. You can have 5 apps which are all named "Files" or "Calculator", but will come from different vendors/developers & have different package names.
Such a method of distinguishing apps could be useful both for the basic filtering engine as well as for the backup/restore mechanism as well, especially across Android versions but would make cross-device restores also a reality.

Personally, such a feature would be P1 for me, as I routinely use anywhere between 3-5 Android devices on a daily basis & setting up the same rules, manually, for each domain, is enough to drive the most mentally resilient person, insane.

**Comment by ignoramous** [comment]
> Backup/restore in my opinion should rely on a consistent method, also for the sake of simplicity, & in my opinion, the only reliable way to do this, is to use package names.

package names are good enough for restores, yes. We're yet to clean that impl up; which is tracked here: #757
